// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nucleus/protos/fastq.proto

#ifndef PROTOBUF_INCLUDED_nucleus_2fprotos_2ffastq_2eproto
#define PROTOBUF_INCLUDED_nucleus_2fprotos_2ffastq_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_nucleus_2fprotos_2ffastq_2eproto 

namespace protobuf_nucleus_2fprotos_2ffastq_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_nucleus_2fprotos_2ffastq_2eproto
namespace nucleus {
namespace genomics {
namespace v1 {
class FastqReaderOptions;
class FastqReaderOptionsDefaultTypeInternal;
extern FastqReaderOptionsDefaultTypeInternal _FastqReaderOptions_default_instance_;
class FastqRecord;
class FastqRecordDefaultTypeInternal;
extern FastqRecordDefaultTypeInternal _FastqRecord_default_instance_;
class FastqWriterOptions;
class FastqWriterOptionsDefaultTypeInternal;
extern FastqWriterOptionsDefaultTypeInternal _FastqWriterOptions_default_instance_;
}  // namespace v1
}  // namespace genomics
}  // namespace nucleus
namespace google {
namespace protobuf {
template<> ::nucleus::genomics::v1::FastqReaderOptions* Arena::CreateMaybeMessage<::nucleus::genomics::v1::FastqReaderOptions>(Arena*);
template<> ::nucleus::genomics::v1::FastqRecord* Arena::CreateMaybeMessage<::nucleus::genomics::v1::FastqRecord>(Arena*);
template<> ::nucleus::genomics::v1::FastqWriterOptions* Arena::CreateMaybeMessage<::nucleus::genomics::v1::FastqWriterOptions>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace nucleus {
namespace genomics {
namespace v1 {

// ===================================================================

class FastqRecord : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.FastqRecord) */ {
 public:
  FastqRecord();
  virtual ~FastqRecord();

  FastqRecord(const FastqRecord& from);

  inline FastqRecord& operator=(const FastqRecord& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FastqRecord(FastqRecord&& from) noexcept
    : FastqRecord() {
    *this = ::std::move(from);
  }

  inline FastqRecord& operator=(FastqRecord&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FastqRecord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FastqRecord* internal_default_instance() {
    return reinterpret_cast<const FastqRecord*>(
               &_FastqRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FastqRecord* other);
  friend void swap(FastqRecord& a, FastqRecord& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FastqRecord* New() const final {
    return CreateMaybeMessage<FastqRecord>(NULL);
  }

  FastqRecord* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FastqRecord>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FastqRecord& from);
  void MergeFrom(const FastqRecord& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FastqRecord* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string description = 2;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // string sequence = 3;
  void clear_sequence();
  static const int kSequenceFieldNumber = 3;
  const ::std::string& sequence() const;
  void set_sequence(const ::std::string& value);
  #if LANG_CXX11
  void set_sequence(::std::string&& value);
  #endif
  void set_sequence(const char* value);
  void set_sequence(const char* value, size_t size);
  ::std::string* mutable_sequence();
  ::std::string* release_sequence();
  void set_allocated_sequence(::std::string* sequence);

  // string quality = 4;
  void clear_quality();
  static const int kQualityFieldNumber = 4;
  const ::std::string& quality() const;
  void set_quality(const ::std::string& value);
  #if LANG_CXX11
  void set_quality(::std::string&& value);
  #endif
  void set_quality(const char* value);
  void set_quality(const char* value, size_t size);
  ::std::string* mutable_quality();
  ::std::string* release_quality();
  void set_allocated_quality(::std::string* quality);

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.FastqRecord)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr sequence_;
  ::google::protobuf::internal::ArenaStringPtr quality_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2ffastq_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FastqReaderOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.FastqReaderOptions) */ {
 public:
  FastqReaderOptions();
  virtual ~FastqReaderOptions();

  FastqReaderOptions(const FastqReaderOptions& from);

  inline FastqReaderOptions& operator=(const FastqReaderOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FastqReaderOptions(FastqReaderOptions&& from) noexcept
    : FastqReaderOptions() {
    *this = ::std::move(from);
  }

  inline FastqReaderOptions& operator=(FastqReaderOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FastqReaderOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FastqReaderOptions* internal_default_instance() {
    return reinterpret_cast<const FastqReaderOptions*>(
               &_FastqReaderOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(FastqReaderOptions* other);
  friend void swap(FastqReaderOptions& a, FastqReaderOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FastqReaderOptions* New() const final {
    return CreateMaybeMessage<FastqReaderOptions>(NULL);
  }

  FastqReaderOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FastqReaderOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FastqReaderOptions& from);
  void MergeFrom(const FastqReaderOptions& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FastqReaderOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool skip_invalid_records = 2;
  void clear_skip_invalid_records();
  static const int kSkipInvalidRecordsFieldNumber = 2;
  bool skip_invalid_records() const;
  void set_skip_invalid_records(bool value);

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.FastqReaderOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool skip_invalid_records_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2ffastq_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FastqWriterOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.FastqWriterOptions) */ {
 public:
  FastqWriterOptions();
  virtual ~FastqWriterOptions();

  FastqWriterOptions(const FastqWriterOptions& from);

  inline FastqWriterOptions& operator=(const FastqWriterOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FastqWriterOptions(FastqWriterOptions&& from) noexcept
    : FastqWriterOptions() {
    *this = ::std::move(from);
  }

  inline FastqWriterOptions& operator=(FastqWriterOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FastqWriterOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FastqWriterOptions* internal_default_instance() {
    return reinterpret_cast<const FastqWriterOptions*>(
               &_FastqWriterOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(FastqWriterOptions* other);
  friend void swap(FastqWriterOptions& a, FastqWriterOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FastqWriterOptions* New() const final {
    return CreateMaybeMessage<FastqWriterOptions>(NULL);
  }

  FastqWriterOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FastqWriterOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FastqWriterOptions& from);
  void MergeFrom(const FastqWriterOptions& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FastqWriterOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.FastqWriterOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2ffastq_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FastqRecord

// string id = 1;
inline void FastqRecord::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FastqRecord::id() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.FastqRecord.id)
  return id_.GetNoArena();
}
inline void FastqRecord::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.FastqRecord.id)
}
#if LANG_CXX11
inline void FastqRecord::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.FastqRecord.id)
}
#endif
inline void FastqRecord::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.FastqRecord.id)
}
inline void FastqRecord::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.FastqRecord.id)
}
inline ::std::string* FastqRecord::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.FastqRecord.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FastqRecord::release_id() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.FastqRecord.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FastqRecord::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.FastqRecord.id)
}

// string description = 2;
inline void FastqRecord::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FastqRecord::description() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.FastqRecord.description)
  return description_.GetNoArena();
}
inline void FastqRecord::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.FastqRecord.description)
}
#if LANG_CXX11
inline void FastqRecord::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.FastqRecord.description)
}
#endif
inline void FastqRecord::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.FastqRecord.description)
}
inline void FastqRecord::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.FastqRecord.description)
}
inline ::std::string* FastqRecord::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.FastqRecord.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FastqRecord::release_description() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.FastqRecord.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FastqRecord::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.FastqRecord.description)
}

// string sequence = 3;
inline void FastqRecord::clear_sequence() {
  sequence_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FastqRecord::sequence() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.FastqRecord.sequence)
  return sequence_.GetNoArena();
}
inline void FastqRecord::set_sequence(const ::std::string& value) {
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.FastqRecord.sequence)
}
#if LANG_CXX11
inline void FastqRecord::set_sequence(::std::string&& value) {
  
  sequence_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.FastqRecord.sequence)
}
#endif
inline void FastqRecord::set_sequence(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.FastqRecord.sequence)
}
inline void FastqRecord::set_sequence(const char* value, size_t size) {
  
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.FastqRecord.sequence)
}
inline ::std::string* FastqRecord::mutable_sequence() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.FastqRecord.sequence)
  return sequence_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FastqRecord::release_sequence() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.FastqRecord.sequence)
  
  return sequence_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FastqRecord::set_allocated_sequence(::std::string* sequence) {
  if (sequence != NULL) {
    
  } else {
    
  }
  sequence_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sequence);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.FastqRecord.sequence)
}

// string quality = 4;
inline void FastqRecord::clear_quality() {
  quality_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FastqRecord::quality() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.FastqRecord.quality)
  return quality_.GetNoArena();
}
inline void FastqRecord::set_quality(const ::std::string& value) {
  
  quality_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.FastqRecord.quality)
}
#if LANG_CXX11
inline void FastqRecord::set_quality(::std::string&& value) {
  
  quality_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.FastqRecord.quality)
}
#endif
inline void FastqRecord::set_quality(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  quality_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.FastqRecord.quality)
}
inline void FastqRecord::set_quality(const char* value, size_t size) {
  
  quality_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.FastqRecord.quality)
}
inline ::std::string* FastqRecord::mutable_quality() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.FastqRecord.quality)
  return quality_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FastqRecord::release_quality() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.FastqRecord.quality)
  
  return quality_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FastqRecord::set_allocated_quality(::std::string* quality) {
  if (quality != NULL) {
    
  } else {
    
  }
  quality_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), quality);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.FastqRecord.quality)
}

// -------------------------------------------------------------------

// FastqReaderOptions

// bool skip_invalid_records = 2;
inline void FastqReaderOptions::clear_skip_invalid_records() {
  skip_invalid_records_ = false;
}
inline bool FastqReaderOptions::skip_invalid_records() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.FastqReaderOptions.skip_invalid_records)
  return skip_invalid_records_;
}
inline void FastqReaderOptions::set_skip_invalid_records(bool value) {
  
  skip_invalid_records_ = value;
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.FastqReaderOptions.skip_invalid_records)
}

// -------------------------------------------------------------------

// FastqWriterOptions

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace genomics
}  // namespace nucleus

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_nucleus_2fprotos_2ffastq_2eproto
