[tool.poetry]
name = "kangaroo"
version = "0.1.0"
description = "Find the absolute path of the desired file in parent directories."
readme = "README.md"
authors = ["Fatih Sarhan <f9n@protonmail.com>"]
homepage = "https://github.com/f9n/kangaroo"
repository = "https://github.com/f9n/kangaroo"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = { version = "^18.9b0", python = "^3.6" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"