# Generated by Django 2.1.3 on 2018-11-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='election.Candidate'),
        ),
    ]
