# Generated by Django 2.1.3 on 2018-12-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20181126_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsement',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='person',
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorser',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
