package:
  name: pyctest
  version: '0.0.9'

build:
  number: 0
  binary_relocation: False
  script_env:
  - TMPDIR
  - CC
  - CXX
  - CPATH
  - LD_LIBRARY_PATH
  - DYLD_LIBRARY_PATH
  - PYCTEST_BUILD_TYPE
  - CMAKE_PREFIX_PATH
  - PYCTEST_CMAKE_PREFIX_PATH
  - PYCTEST_CMAKE_INCLUDE_PATH
  - PYCTEST_CMAKE_LIBRARY_PATH
  script:
    - "{{ PYTHON }} setup.py install"

source:
  git_rev: 88df2b8f5c875e3f4127fd71ee0f9fe9caa1293d
  git_url: https://github.com/jrmadsen/pyctest.git

requirements:
  host:
  - python={{ python }}
  - setuptools
  - cmake
  - openssl
  - curl
  run:
  - python={{ python }}
  - openssl
  - curl

test:
  imports:
  - pyctest
  - pyctest.pyctest
  - pyctest.pycmake
  - pyctest.helpers

about:
  home: https://jrmadsen.github.io/pyctest/
  license: MIT
  summary: "Python bindings to select portions of CMake/CTest package -- enabling generation of CTests for CDash submission without a CMake build system"
