# Generated by Django 2.1.3 on 2018-11-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boris', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
