# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_time__',
    '__build_status__'
]

__version__ = '0.1.1'
__version_short__ = '0.1.1'
__version_long__ = '0.1.1-0-gb6f37bad'
__version_post__ = '0'
__version_commit__ = 'b6f37bad'
__version_date__ = '2018-12-11 15:55:07 -0500'
__version_dirty__ = False
__build_date__ = '2018-12-12'
__build_time__ = '12:25:49.975671'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
