# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_Project_hydrant.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.InputFeaturesBox = QtWidgets.QGroupBox(self.centralwidget)
        self.InputFeaturesBox.setObjectName("InputFeaturesBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.InputFeaturesBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.OpenHydrantLbl = QtWidgets.QLabel(self.InputFeaturesBox)
        self.OpenHydrantLbl.setToolTip("")
        self.OpenHydrantLbl.setObjectName("OpenHydrantLbl")
        self.gridLayout_2.addWidget(self.OpenHydrantLbl, 0, 0, 1, 1)
        self.OpenHydrantShapefileTB = QtWidgets.QToolButton(self.InputFeaturesBox)
        self.OpenHydrantShapefileTB.setObjectName("OpenHydrantShapefileTB")
        self.gridLayout_2.addWidget(self.OpenHydrantShapefileTB, 0, 2, 1, 1)
        self.OpenInspAreaShapefileTB = QtWidgets.QToolButton(self.InputFeaturesBox)
        self.OpenInspAreaShapefileTB.setObjectName("OpenInspAreaShapefileTB")
        self.gridLayout_2.addWidget(self.OpenInspAreaShapefileTB, 1, 2, 1, 1)
        self.OpenInspAreaShapefileLE = QtWidgets.QLineEdit(self.InputFeaturesBox)
        self.OpenInspAreaShapefileLE.setObjectName("OpenInspAreaShapefileLE")
        self.gridLayout_2.addWidget(self.OpenInspAreaShapefileLE, 1, 1, 1, 1)
        self.OpenInspAreaLbl = QtWidgets.QLabel(self.InputFeaturesBox)
        self.OpenInspAreaLbl.setObjectName("OpenInspAreaLbl")
        self.gridLayout_2.addWidget(self.OpenInspAreaLbl, 1, 0, 1, 1)
        self.OpenHydrantShapefileLE = QtWidgets.QLineEdit(self.InputFeaturesBox)
        self.OpenHydrantShapefileLE.setObjectName("OpenHydrantShapefileLE")
        self.gridLayout_2.addWidget(self.OpenHydrantShapefileLE, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.InputFeaturesBox, 1, 0, 1, 1)
        self.CreateFetureBox = QtWidgets.QGroupBox(self.centralwidget)
        self.CreateFetureBox.setObjectName("CreateFetureBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CreateFetureBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputPathLE = QtWidgets.QLineEdit(self.CreateFetureBox)
        self.outputPathLE.setObjectName("outputPathLE")
        self.gridLayout_3.addWidget(self.outputPathLE, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.outputPathTB = QtWidgets.QToolButton(self.CreateFetureBox)
        self.outputPathTB.setObjectName("outputPathTB")
        self.gridLayout_3.addWidget(self.outputPathTB, 0, 2, 1, 1)
        self.outputPathLbl = QtWidgets.QLabel(self.CreateFetureBox)
        self.outputPathLbl.setObjectName("outputPathLbl")
        self.gridLayout_3.addWidget(self.outputPathLbl, 0, 0, 1, 1)
        self.shapefileCreateNewPB = QtWidgets.QPushButton(self.CreateFetureBox)
        self.shapefileCreateNewPB.setObjectName("shapefileCreateNewPB")
        self.gridLayout_3.addWidget(self.shapefileCreateNewPB, 2, 0, 1, 1)
        self.fileNameLbl = QtWidgets.QLabel(self.CreateFetureBox)
        self.fileNameLbl.setObjectName("fileNameLbl")
        self.gridLayout_3.addWidget(self.fileNameLbl, 1, 0, 1, 1)
        self.fileNameLE = QtWidgets.QLineEdit(self.CreateFetureBox)
        self.fileNameLE.setObjectName("fileNameLE")
        self.gridLayout_3.addWidget(self.fileNameLE, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.CreateFetureBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Select Hydrants by Area"))
        self.InputFeaturesBox.setTitle(_translate("MainWindow", "Input Features"))
        self.OpenHydrantLbl.setText(_translate("MainWindow", "Select Fire Hydrant Shapefile: "))
        self.OpenHydrantShapefileTB.setToolTip(_translate("MainWindow", "Navigate to the hydrant shapefile"))
        self.OpenHydrantShapefileTB.setText(_translate("MainWindow", "..."))
        self.OpenInspAreaShapefileTB.setToolTip(_translate("MainWindow", "Navigate to the inspection area shapefile"))
        self.OpenInspAreaShapefileTB.setText(_translate("MainWindow", "..."))
        self.OpenInspAreaShapefileLE.setToolTip(_translate("MainWindow", "Displays the name and path of the inspection area shapefile"))
        self.OpenInspAreaLbl.setText(_translate("MainWindow", "Select Inspection Area Shapefile:"))
        self.OpenHydrantShapefileLE.setToolTip(_translate("MainWindow", "Displays the name and path of the hydrant shapefile"))
        self.CreateFetureBox.setTitle(_translate("MainWindow", "Output Feature"))
        self.outputPathLE.setToolTip(_translate("MainWindow", "Displays the path for the output shapefile"))
        self.outputPathTB.setToolTip(_translate("MainWindow", "Navigate to the location to save the shapefile"))
        self.outputPathTB.setText(_translate("MainWindow", "..."))
        self.outputPathLbl.setText(_translate("MainWindow", "Select Output Path:"))
        self.shapefileCreateNewPB.setToolTip(_translate("MainWindow", "Click this button to create new shapefile using the input features above"))
        self.shapefileCreateNewPB.setText(_translate("MainWindow", "Create Shapefile"))
        self.fileNameLbl.setText(_translate("MainWindow", "Enter File Name:"))
        self.fileNameLE.setToolTip(_translate("MainWindow", "Please name the shapefile"))
        self.actionExit.setText(_translate("MainWindow", "Close"))
        self.actionExit.setToolTip(_translate("MainWindow", "Close the form"))

