# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_Project_stormdrains.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.CreateFetureBox = QtWidgets.QGroupBox(self.centralwidget)
        self.CreateFetureBox.setObjectName("CreateFetureBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CreateFetureBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputPathLE = QtWidgets.QLineEdit(self.CreateFetureBox)
        self.outputPathLE.setObjectName("outputPathLE")
        self.gridLayout_3.addWidget(self.outputPathLE, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.outputPathTB = QtWidgets.QToolButton(self.CreateFetureBox)
        self.outputPathTB.setObjectName("outputPathTB")
        self.gridLayout_3.addWidget(self.outputPathTB, 0, 2, 1, 1)
        self.outputPathLbl = QtWidgets.QLabel(self.CreateFetureBox)
        self.outputPathLbl.setObjectName("outputPathLbl")
        self.gridLayout_3.addWidget(self.outputPathLbl, 0, 0, 1, 1)
        self.shapefileCreateNewPB = QtWidgets.QPushButton(self.CreateFetureBox)
        self.shapefileCreateNewPB.setObjectName("shapefileCreateNewPB")
        self.gridLayout_3.addWidget(self.shapefileCreateNewPB, 2, 0, 1, 1)
        self.fileNameLbl = QtWidgets.QLabel(self.CreateFetureBox)
        self.fileNameLbl.setObjectName("fileNameLbl")
        self.gridLayout_3.addWidget(self.fileNameLbl, 1, 0, 1, 1)
        self.fileNameLE = QtWidgets.QLineEdit(self.CreateFetureBox)
        self.fileNameLE.setObjectName("fileNameLE")
        self.gridLayout_3.addWidget(self.fileNameLE, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.CreateFetureBox, 2, 0, 1, 1)
        self.InputFeaturesBox = QtWidgets.QGroupBox(self.centralwidget)
        self.InputFeaturesBox.setObjectName("InputFeaturesBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.InputFeaturesBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.OpenStormBasinShapefileLE = QtWidgets.QLineEdit(self.InputFeaturesBox)
        self.OpenStormBasinShapefileLE.setObjectName("OpenStormBasinShapefileLE")
        self.gridLayout_2.addWidget(self.OpenStormBasinShapefileLE, 1, 1, 1, 1)
        self.OpenStormBasinShapefileTB = QtWidgets.QToolButton(self.InputFeaturesBox)
        self.OpenStormBasinShapefileTB.setObjectName("OpenStormBasinShapefileTB")
        self.gridLayout_2.addWidget(self.OpenStormBasinShapefileTB, 1, 2, 1, 1)
        self.OpenStormdrainShapefileTB = QtWidgets.QToolButton(self.InputFeaturesBox)
        self.OpenStormdrainShapefileTB.setObjectName("OpenStormdrainShapefileTB")
        self.gridLayout_2.addWidget(self.OpenStormdrainShapefileTB, 0, 2, 1, 1)
        self.OpenStormdrainLbl = QtWidgets.QLabel(self.InputFeaturesBox)
        self.OpenStormdrainLbl.setToolTip("")
        self.OpenStormdrainLbl.setObjectName("OpenStormdrainLbl")
        self.gridLayout_2.addWidget(self.OpenStormdrainLbl, 0, 0, 1, 1)
        self.OpenStormdrainShapefileLE = QtWidgets.QLineEdit(self.InputFeaturesBox)
        self.OpenStormdrainShapefileLE.setObjectName("OpenStormdrainShapefileLE")
        self.gridLayout_2.addWidget(self.OpenStormdrainShapefileLE, 0, 1, 1, 1)
        self.OpenStormBasinLbl = QtWidgets.QLabel(self.InputFeaturesBox)
        self.OpenStormBasinLbl.setObjectName("OpenStormBasinLbl")
        self.gridLayout_2.addWidget(self.OpenStormBasinLbl, 1, 0, 1, 1)
        self.PickStormBasinLbl = QtWidgets.QLabel(self.InputFeaturesBox)
        self.PickStormBasinLbl.setObjectName("PickStormBasinLbl")
        self.gridLayout_2.addWidget(self.PickStormBasinLbl, 2, 0, 1, 1)
        self.PickStormBasinCB = QtWidgets.QComboBox(self.InputFeaturesBox)
        self.PickStormBasinCB.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.PickStormBasinCB.setObjectName("PickStormBasinCB")
        self.gridLayout_2.addWidget(self.PickStormBasinCB, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.InputFeaturesBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Select Stormdrains by Draiange Basin"))
        self.CreateFetureBox.setTitle(_translate("MainWindow", "Output Feature"))
        self.outputPathLE.setToolTip(_translate("MainWindow", "Displays the path for the output shapefile"))
        self.outputPathTB.setToolTip(_translate("MainWindow", "Navigate to the location to save the shapefile"))
        self.outputPathTB.setText(_translate("MainWindow", "..."))
        self.outputPathLbl.setText(_translate("MainWindow", "Select Output Path:"))
        self.shapefileCreateNewPB.setToolTip(_translate("MainWindow", "Click this button to create new shapefile using the input features above"))
        self.shapefileCreateNewPB.setText(_translate("MainWindow", "Create Shapefile"))
        self.fileNameLbl.setText(_translate("MainWindow", "Enter File Name:"))
        self.fileNameLE.setToolTip(_translate("MainWindow", "Please name the shapefile"))
        self.InputFeaturesBox.setTitle(_translate("MainWindow", "Input Features"))
        self.OpenStormBasinShapefileLE.setToolTip(_translate("MainWindow", "Displays the name and path of the drainage basin shapefile"))
        self.OpenStormBasinShapefileTB.setToolTip(_translate("MainWindow", "Navigate to the drainage basin feature class"))
        self.OpenStormBasinShapefileTB.setText(_translate("MainWindow", "..."))
        self.OpenStormdrainShapefileTB.setToolTip(_translate("MainWindow", "Navigate to the stormdrain shapefile"))
        self.OpenStormdrainShapefileTB.setText(_translate("MainWindow", "..."))
        self.OpenStormdrainLbl.setText(_translate("MainWindow", "Select Stormdrain Shapefile: "))
        self.OpenStormdrainShapefileLE.setToolTip(_translate("MainWindow", "Displays the name and path of the stormdrain shapefile"))
        self.OpenStormBasinLbl.setText(_translate("MainWindow", "Select Drainage Basin Shapefile:"))
        self.PickStormBasinLbl.setText(_translate("MainWindow", "Select Stormwater Drainage Basin:"))
        self.PickStormBasinCB.setToolTip(_translate("MainWindow", "Pick a stormwater drainage basin from the list"))
        self.actionExit.setText(_translate("MainWindow", "Close"))
        self.actionExit.setToolTip(_translate("MainWindow", "Close the form"))

