language: python
dist: xenial
python:
    - 3.6
    - 3.7
install:
    - pip install pytest coverage coveralls flake8
    - pip install -e .
script:
    - coverage run -m pytest tests.py
    - coverage report -m --fail-under=100
    - flake8 *.py
after_script:
    - coveralls
notifications:
    email: false
