
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-17T08:16:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc21b39e8075f7cf05dbdb76278c2f0c8924f28b",
 "version": "v0.4.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
