
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-08T14:20:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "491d7905554b8a9ec5ce70e95b57789d6a35b2f4",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
