[tool.poetry]
name = "statuslight_client"
version = "0.1.0"
description = ""
authors = ["Daniel Bengtsson <daniel.f.bengtsson@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pyserial = "^3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
