version: 2
jobs:
  test:
    docker:
      - image: reelio/ssr:ci
    environment:
      BASH_ENV: ~/.bashrc
    steps:
      - checkout
      - restore_cache:
          keys:
            - ssr-tox-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - restore_cache:
          keys:
            - ssr-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install dev requirements
          command: ./bin/install
      - run:
          name: Run the tests
          command: ./bin/test
      - run:
          name: Report coverage
          command: |
            source venv/bin/activate
            codecov
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
      - save_cache:
          key: ssr-tox-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - ./.tox
      - save_cache:
          key: ssr-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - ./venv

  deploy:
    docker:
      - image: reelio/ssr:ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - ssr-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install dev requirements
          command: ./bin/install
      - run:
          name: Deploy
          command: ./bin/deploy

workflows:
  version: 2
  build-envs:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only:
                - /[0-9](\.[0-9]+)*/
            branches:
              ignore: /.*/
