
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-12T18:41:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5c32937acf4bef1eec6e448b0c7765856d78eed",
 "version": "0.6.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
