
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-03T09:34:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7fb817e8f992bd5c6a287f5afb5e999a1e29449",
 "version": "0.21.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
