
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a07e961d66f62d4e00571f741e22448ed0aead60",
 "version": "2042"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
