
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-29T17:35:25-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6dfbedd85561a9f72a409a6f108a96fc74dc5ef5",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
