
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-07T15:30:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a44861eaad86652ea840efaf3f4cd06e28bcd5f",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
