
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-28T17:32:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e21c5de51b5cd0b1b11cc1c63fe91bed3ba97a0",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
