- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
    check:
      jobs:
        - freezer-web-ui-ubuntu-xenial:
            voting: true

        - openstack-tox-lower-constraints
        - openstack-tox-pylint
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-pylint
- job:
    name: freezer-web-ui-ubuntu-xenial
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-web-ui-ubuntu-xenial/run.yaml
    post-run: playbooks/legacy/freezer-web-ui-ubuntu-xenial/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient

