
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-30T10:37:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "39acccff21ea4604bb95b594f527efba5c238a28",
 "version": "0.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
