# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2018-12-01 20:09:29 UTC
from __future__ import unicode_literals
import datetime

version = "2.0.7"
githash = "54d4ca984ec81321001f72c888076376381ec0a6"


major = 2
minor = 0
bugfix = 7

release = True
timestamp = datetime.datetime(2018, 12, 1, 20, 9, 29)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
