dist: xenial

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - python-gst-1.0

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8
  - TOX_ENV=check-manifest

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi

notifications:
  irc:
    channels:
      - irc.freenode.org#mopidy
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
