- name: Creating supervisor configuration file...
  template:
    src: ../../../configuration/templates/supervisord.conf.j2
    dest: '{{ control_server_configuration.supervisor_configuration_file }}'
