[tool.poetry]
name = "vmongodb"
version = "0.1.2"
description = ""
authors = ["Flavio <fvilante1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pymongo = "^3.7.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
