
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2018-12-07T19:47:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26b0583bb08c9207fbcc2589aba46a8aafbab1be",
 "version": "2018.12.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
