
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-06T17:35:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "096c08e975a75a95c591feb6365a518fec887f9d",
 "version": "2018.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
