codecov:
  ci:
    - "!ci.appveyor.com"

coverage:
  status:
    project:
      default:
        enabled: yes
        target: auto
    patch:
      default:
        enabled: yes
        target: 100%
    changes: no
