name: Bruteforce Passwords
cwe: 307
categories: [attack]
description: The application allows multiple/consecutive attempts at authentication (bruteforce).
mitigations:
- description: Ensure that users are locked out for a certain timeframe/till administrator's intervention when multiple
    authentication attempts are encountered.
  phase: Architecture and Design
- description: Log invalid access attempts to ensure that potentially malicious bruteforce attempts are logged
  phase: Architecture and Design
test-cases:
- name: automated-vulnerability-scanning
  test: run automated vulnerability discovery tools and bruteforce against the application
  tools: [zap,burpsuite,arachni,acunetix,netsparker,appspider,w3af]
  type: discovery
