name: Weak/Default Passwords
cwe: 521
categories: [app_vulns,owasp]
description: The application allows the users to set default or weak passwords
mitigations:
- description: Ensure that passwords set in the application are mandatorily strong.
  phase: Architecture and Design
- description: Prevent Credential Stuffing by validating user passwords against Database of compromised passwords
  phase: Architecture and Design
test-cases:
- name: automated-vulnerability-scanning
  test: run automated vulnerability discovery tools and bruteforce against the application
  tools: [zap,burpsuite,arachni,acunetix,netsparker,appspider,w3af]
  type: discovery