# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTag',
        ),
    ]
