# Generated by Django 2.1.2 on 2018-12-07 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields

from kip.app_settings import DocumentStorageClass


DocumentStorage = DocumentStorageClass()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.FileField(storage=DocumentStorage, upload_to='')),
                ('is_pinned', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPFSLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('crawled_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boris.CrawledItem')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipfs_page', to='kip.IPFSFile')),
                ('embedded_files', models.ManyToManyField(to='kip.IPFSFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
