# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/travis/build/randovania/randovania/randovania/gui/iso_management_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ISOManagementWindow(object):
    def setupUi(self, ISOManagementWindow):
        ISOManagementWindow.setObjectName("ISOManagementWindow")
        ISOManagementWindow.resize(852, 607)
        self.centralWidget = QtWidgets.QWidget(ISOManagementWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.files_box = QtWidgets.QGroupBox(self.centralWidget)
        self.files_box.setMaximumSize(QtCore.QSize(16777215, 80))
        self.files_box.setObjectName("files_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.files_box)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.change_files_location_button = QtWidgets.QPushButton(self.files_box)
        self.change_files_location_button.setObjectName("change_files_location_button")
        self.gridLayout_3.addWidget(self.change_files_location_button, 1, 0, 1, 1)
        self.delete_files_button = QtWidgets.QPushButton(self.files_box)
        self.delete_files_button.setObjectName("delete_files_button")
        self.gridLayout_3.addWidget(self.delete_files_button, 1, 2, 1, 1)
        self.reset_files_location_button = QtWidgets.QPushButton(self.files_box)
        self.reset_files_location_button.setObjectName("reset_files_location_button")
        self.gridLayout_3.addWidget(self.reset_files_location_button, 1, 1, 1, 1)
        self.current_files_location_label = QtWidgets.QLabel(self.files_box)
        self.current_files_location_label.setEnabled(True)
        self.current_files_location_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.current_files_location_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_files_location_label.setObjectName("current_files_location_label")
        self.gridLayout_3.addWidget(self.current_files_location_label, 0, 0, 1, 1)
        self.files_location = QtWidgets.QLabel(self.files_box)
        self.files_location.setObjectName("files_location")
        self.gridLayout_3.addWidget(self.files_location, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.files_box, 1, 0, 1, 2)
        self.iso_box = QtWidgets.QGroupBox(self.centralWidget)
        self.iso_box.setMaximumSize(QtCore.QSize(16777215, 120))
        self.iso_box.setObjectName("iso_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.iso_box)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.load_iso_button = QtWidgets.QPushButton(self.iso_box)
        self.load_iso_button.setObjectName("load_iso_button")
        self.gridLayout_4.addWidget(self.load_iso_button, 0, 0, 1, 1)
        self.package_iso_button = QtWidgets.QPushButton(self.iso_box)
        self.package_iso_button.setObjectName("package_iso_button")
        self.gridLayout_4.addWidget(self.package_iso_button, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.iso_box, 3, 0, 1, 2)
        self.game_patching = QtWidgets.QGroupBox(self.centralWidget)
        self.game_patching.setObjectName("game_patching")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.game_patching)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.show_advanced_options_check = QtWidgets.QCheckBox(self.game_patching)
        self.show_advanced_options_check.setObjectName("show_advanced_options_check")
        self.gridLayout_6.addWidget(self.show_advanced_options_check, 5, 0, 1, 1)
        self.remove_hud_popup_check = QtWidgets.QCheckBox(self.game_patching)
        self.remove_hud_popup_check.setObjectName("remove_hud_popup_check")
        self.gridLayout_6.addWidget(self.remove_hud_popup_check, 0, 0, 1, 1)
        self.include_menu_mod_check = QtWidgets.QCheckBox(self.game_patching)
        self.include_menu_mod_check.setEnabled(True)
        self.include_menu_mod_check.setObjectName("include_menu_mod_check")
        self.gridLayout_6.addWidget(self.include_menu_mod_check, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.game_patching)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.game_patching)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.game_patching)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.game_patching, 0, 0, 1, 2)
        ISOManagementWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ISOManagementWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menuBar.setObjectName("menuBar")
        ISOManagementWindow.setMenuBar(self.menuBar)

        self.retranslateUi(ISOManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(ISOManagementWindow)

    def retranslateUi(self, ISOManagementWindow):
        _translate = QtCore.QCoreApplication.translate
        ISOManagementWindow.setWindowTitle(_translate("ISOManagementWindow", "Hello, world!"))
        self.files_box.setTitle(_translate("ISOManagementWindow", "File Location"))
        self.change_files_location_button.setText(_translate("ISOManagementWindow", "Change"))
        self.delete_files_button.setText(_translate("ISOManagementWindow", "Delete contents"))
        self.reset_files_location_button.setText(_translate("ISOManagementWindow", "Use Default Location"))
        self.current_files_location_label.setText(_translate("ISOManagementWindow", "Current Files Location:"))
        self.files_location.setText(_translate("ISOManagementWindow", "<CHANGE ME>"))
        self.iso_box.setTitle(_translate("ISOManagementWindow", "ISO Operations"))
        self.load_iso_button.setToolTip(_translate("ISOManagementWindow", "Extracts an Game ISO to the current files location"))
        self.load_iso_button.setText(_translate("ISOManagementWindow", "Load ISO"))
        self.package_iso_button.setToolTip(_translate("ISOManagementWindow", "Creates an ISO based on the contents of the current files location"))
        self.package_iso_button.setText(_translate("ISOManagementWindow", "Package as ISO"))
        self.game_patching.setTitle(_translate("ISOManagementWindow", "Game Patching"))
        self.show_advanced_options_check.setText(_translate("ISOManagementWindow", "Show advanced options"))
        self.remove_hud_popup_check.setToolTip(_translate("ISOManagementWindow", "The \"HUD Popup\" is the popup that appears after you collect an item"))
        self.remove_hud_popup_check.setText(_translate("ISOManagementWindow", "Remove HUD popup"))
        self.include_menu_mod_check.setText(_translate("ISOManagementWindow", "Include Menu Mod"))
        self.label_3.setText(_translate("ISOManagementWindow", "<html><head/><body><p>Menu Mod is a pratice tool for Echoes, allowing in-game changes to which items you have and warping to all rooms.</p><p>See the <a href=\"https://www.dropbox.com/s/yhqqafaxfo3l4vn/Echoes%20Menu.7z?file_subpath=%2FEchoes+Menu%2Freadme.txt\"><span style=\" text-decoration: underline; color:#0000ff;\">Menu Mod README</span></a> for more details.</p><p><br/></p></body></html>"))
        self.label.setText(_translate("ISOManagementWindow", "<html><head/><body><p>Enables the advanced game patching options. It\'s recommended to leave this option <span style=\" font-weight:600;\">disabled</span> unless you know what you\'re doing.</p></body></html>"))
        self.label_2.setText(_translate("ISOManagementWindow", "<html><head/><body><p>Replaces the &quot;Item Adquired&quot; popup after collecting an item with an alert.</p><p><br/></p></body></html>"))

