__version__ = "0.0.7"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.0.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'fcc3de45dfe7fc378a2b782dcd91c561aba739b6'
__git_head_subject__ = u'Finished Release v0.0.7'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-12-10 17:00:39'
