swagger: '2.0'
info:
  title: Please add a title
  description: Please add a description
  contact:
    name: Please add a contact name
  version: '0.0.0'
  x-visibility: unlisted
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization

security:
  - Bearer: []
