[tool.poetry]
name = "pyramid-ssm-settings"
version = "0.2.0"
description = "Pull settings into Pyramid from Amazon EC2 Parameter Store."
readme = "README.md"
homepage = "https://github.com/luhn/pyramid-ssm-settings"
repository = "https://github.com/luhn/pyramid-ssm-settings"
authors = ["Theron Luhn <theron@luhn.com>"]
license = "MIT"
classifiers = [
	"Development Status :: 3 - Alpha",
	"Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.4"
boto3 = "^1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
