version: '3'

services:

  totembionet:
    container_name: totembionet
    image: totembionet
    ports:
      - "8888:8888"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4.0
    ports:
      - "27017:27017"



