
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-08T15:06:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a69a235ff70eb46a520e688e5577f314c11746d4",
 "version": "1.0a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
