
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-17T21:49:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4fe89d0618c7e140a51a7c216e8842bcfa80982",
 "version": "v1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
