# Autogenerated by Astropy's setup.py on 2018-11-28 06:43:03 UTC
from __future__ import unicode_literals
import datetime

version = "3.1rc2"
githash = "2ed73b0343c9e63fd1be8eb25cfe229901c78327"


major = 3
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2018, 11, 28, 6, 43, 3)
debug = False

astropy_helpers_version = "3.1rc1"

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
