
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-06T09:49:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7da1733eb65d84c95d1c71dfc32173c7d8f4417a",
 "version": "1.3.0.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
