language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
git:
  depth: false
install:
  - pip install coveralls
  - python setup.py install
  - wget https://www.dropbox.com/s/sidecqpk6dhgsdq/song.zip
  - unzip song.zip
  - sudo apt-get install mpg123 -y
script:
  - coverage run --source=foucluster --omit=env tests.py
  - coveralls
branches:
  only:
    - master
    - dev
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
