# Generated by Django 2.0.8 on 2018-09-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionnight', '0005_auto_20180304_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apelectionmeta',
            name='ballot_measure',
        ),
        migrations.RemoveField(
            model_name='apelectionmeta',
            name='election',
        ),
        migrations.DeleteModel(
            name='APElectionMeta',
        ),
    ]
