# Generated by Django 2.0.8 on 2018-10-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_race_description'),
        ('electionnight', '0006_auto_20180919_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='featured',
            field=models.ManyToManyField(to='election.Election'),
        ),
    ]
