[tool.poetry]
name = "poi_kml"
version = "0.1.1"
description = ""
authors = ["Manny Ochoa <dev@manuelochoa.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.23.4"
simplekml = "^1.3"
uszipcode = "^0.2.2"
geocoder = "^1.38"
pathlib = "^1.0"
faker = "^1.0"
usaddress = "^0.5.10"
phonenumbers = "^8.10"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
