__version__ = "0.1.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.1.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8ae9b93ce9dcc1d29b5118683c185fb73f3dd2dd'
__git_head_subject__ = u'Finished Release v0.1.7'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-12-20 17:21:07'
