sudo: false
language: python
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3'
install:
  - pip install -U pip
  - pip install -U wheel
  - pip install tox-travis
script: tox
