language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
jobs:
  include:
      - python: 3.7
        dist: xenial
script:
  - coverage run -m zope.testrunner --test-path=src
  - coverage run -a -m sphinx -b doctest -d docs/_build/doctrees docs docs/_build/doctest
after_success:
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test,docs]"


cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
