
- instance:
    input:
        name: genetalk_db_machine 
        image_id: ami-8e2729f5 
        keyname: gcta-us-east-1-access-key 
        subnet_id:
            value: subnet-83950fe6 
        number: 1
        instance_type: r4.large 
        security_group_ids:
            value: [sg-9f3a7ee3]
        tags:
            - tag:
                key: Name
                value: gtxcloud_condor_submitor 

        spot:
            price: 1
            wait_until_complete: 1
    #  volumes:
    #       value: [vol-03c044b95b80ce2d1]

        private_ip: 172.31.74.224
    #        public_ip: 52.87.131.40 


- instance:
    input:
        name: genetalk_db_machine 
        image_id: ami-877974fc 
        keyname: gcta-us-east-1-access-key 
        subnet_id:
            value: subnet-83950fe6 
        number: 1 
        instance_type: r4.large 
        security_group_ids:
            value: [sg-9f3a7ee3]
        tags:
            - tag:
                key: Name
                value: gtxcloud_condor_executor 

        spot:
            price: 1
            wait_until_complete: 1

