
- subnet:
    input:
        cidr: 13.12.0.0
        mask: 20
        vpc_id:
            value: vpc-ebc9628c
        publicip: 1
        availability_zone: us-east-1a 
        tags:
            - tag:
                key: Name 
                value: genetalk_subnet
    response:
        Subnet:
            SubnetId:
                export: subnet_id
