
- vpc:
    input:
        cidr: 13.12.0.0
        mask: 20
        tags:
            - tag:
                key: Name 
                value: genetalk_vpc 
    response:
        Vpc:
            VpcId:
                export: vpc_id
    subnet:
        from_config: ./libaws/demo/subnet_config.yaml
    route:
        from_config: ./libaws/demo/route_config.yaml
    security:
        from_config: ./libaws/demo/security_config.yaml

