# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Deploy a Basic OVB Environment Using Neutron port-security
# description: |
#   Deploy an OVB stack that uses the Neutron port-security extension to
#   allow OVB functionality in clouds with security groups enabled.
resource_registry:
  OS::OVB::BMCPort: ../templates/bmc-port-port-security.yaml
  OS::OVB::BaremetalPorts: ../templates/baremetal-ports-default-port-security.yaml
  OS::OVB::UndercloudPorts: ../templates/undercloud-ports-port-security.yaml
