#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['barbacoa',
 'barbacoa.backends',
 'barbacoa.plugins',
 'barbacoa.plugins.mods',
 'barbacoa.plugins.mods.tools',
 'barbacoa.queues',
 'barbacoa.storage',
 'barbacoa.tasks']

package_data = \
{'': ['*']}

extras_require = \
{'dev': ['setuptools_scm'], 'test': ['pytest', 'pytest-cov']}

entry_points = \
{'barbacoa.loader': ['backends = barbacoa.backends',
                     'queues = barbacoa.queues',
                     'storage = barbacoa.storage',
                     'tasks = barbacoa.tasks']}

setup(name='barbacoa',
      version='0.2.2',
      description='Asynchronous task manager using asyncio',
      author='Daniel Wallace',
      author_email='daniel@gtmanfred.com',
      url='https://github.com/SADevs/barbacoa',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      entry_points=entry_points,
     )
