[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "hookmeup"
author = "Daniel Moch"
author-email = "daniel@danielmoch.com"
home-page = "https://git.danielmoch.com/hookmeup"
description-file = "README.md"
classifiers = ["License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Version Control :: Git"]
requires-python=">=2.7"

[tool.flit.metadata.requires-extra]
dev = ['pipenv']

[tool.flit.scripts]
hookmeup = "hookmeup:main"
