language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - python3-pip
before_install:
  - sudo pip3 install flit
install:
  - 'flit install --python "$(which python)"'
script:
  - manly --version
  - py.test
  - manly ls -lAh
