steps:
  - label: ":python: format and test"
    branches: "!v*.*.*"
    command: |
      echo "+++ Running formatter"
      /usr/local/bin/black --check dbp.py
      echo "--- Prepping virtualenv"
      rm -rf .venv
      python3 -mvenv .venv
      .venv/bin/pip install flit
      .venv/bin/flit install -s
      echo "+++ Testing"
      .venv/bin/pytest -s --cov=dbp tests/ --cov-report=xml --cov-report=term
      PATH=$PWD/.venv/bin:$PATH bash <(curl -s https://codecov.io/bash)
  - label: ":python: publish docs and package"
    branches: "v*.*.*"
    agents:
      queue: "deploy"
    command: |
      echo "--- Installing flit and requirements"
      rm -rf .venv
      python3 -mvenv .venv
      .venv/bin/pip install flit
      .venv/bin/flit install -s
      echo "+++ Deploying site"
      .venv/bin/mkdocs gh-deploy --force
      echo "+++ Publishing to PyPi"
      .venv/bin/flit publish
