
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-17T16:34:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "19157576dbe4a8710dc02ecfde27d25f3e349826",
 "version": "v1.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
