# Generated by Django 2.1.1 on 2018-11-28 04:00

from django.db import migrations, models
import django.db.models.deletion
import easy_jsonfield.encoder
import easy_jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('klass_path', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('init_arg', models.CharField(blank=True, max_length=64, null=True)),
                ('generator', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('para', easy_jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'cls': easy_jsonfield.encoder.JSONEncoder, 'ensure_ascii': False, 'indent': 2, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='konfluence.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('category', 'name')},
        ),
    ]
