#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Fri Jul 05 09:53:58 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER | wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.PanelMetaboliteLines = wx.Panel(self, -1)
        self.ScrolledWindowDynamicList = wx.ScrolledWindow(self.PanelMetaboliteLines, -1, style=wx.TAB_TRAVERSAL)
        self.LabelMetaboliteListGridSizerPlaceholder = wx.StaticText(self.ScrolledWindowDynamicList, -1, "MetaboliteListGridSizerPlaceholder")
        self.ButtonSelectAll = wx.Button(self.PanelMetaboliteLines, -1, "Select All")
        self.ButtonDeselectAll = wx.Button(self.PanelMetaboliteLines, -1, "De-Select All")
        self.ButtonAddMetabolite = wx.Button(self.PanelMetaboliteLines, -1, "Add Metabolite")
        self.ButtonRemoveSelected = wx.Button(self.PanelMetaboliteLines, -1, "Remove Selected")
        self.sizer_7_staticbox = wx.StaticBox(self.PanelMetaboliteLines, -1, "Metabolite Lines")
        self.LabelOkCancelPlaceholder = wx.StaticText(self, -1, "LabelOkCancelPlaceholder", style=wx.ALIGN_RIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_select_all, self.ButtonSelectAll)
        self.Bind(wx.EVT_BUTTON, self.on_deselect_all, self.ButtonDeselectAll)
        self.Bind(wx.EVT_BUTTON, self.on_add_metabolite, self.ButtonAddMetabolite)
        self.Bind(wx.EVT_BUTTON, self.on_remove_selected, self.ButtonRemoveSelected)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("User Defined Metabolite Information")
        self.ScrolledWindowDynamicList.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_7_staticbox.Lower()
        sizer_7 = wx.StaticBoxSizer(self.sizer_7_staticbox, wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(1, 6, 5, 5)
        grid_sizer_1.Add(self.LabelMetaboliteListGridSizerPlaceholder, 0, 0, 0)
        self.ScrolledWindowDynamicList.SetSizer(grid_sizer_1)
        sizer_7.Add(self.ScrolledWindowDynamicList, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_8.Add(self.ButtonSelectAll, 0, wx.RIGHT, 5)
        sizer_8.Add(self.ButtonDeselectAll, 0, wx.RIGHT, 5)
        sizer_8.Add(self.ButtonAddMetabolite, 0, wx.RIGHT, 5)
        sizer_8.Add(self.ButtonRemoveSelected, 0, wx.RIGHT, 5)
        sizer_7.Add(sizer_8, 0, wx.TOP | wx.BOTTOM | wx.EXPAND, 5)
        self.PanelMetaboliteLines.SetSizer(sizer_7)
        sizer_1.Add(self.PanelMetaboliteLines, 1, wx.EXPAND, 0)
        sizer_5.Add(self.LabelOkCancelPlaceholder, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_5, 0, wx.RIGHT | wx.TOP | wx.BOTTOM | wx.EXPAND, 10)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def on_select_all(self, event):  # wxGlade: MyDialog.<event_handler>
        print "Event handler `on_select_all' not implemented!"
        event.Skip()

    def on_deselect_all(self, event):  # wxGlade: MyDialog.<event_handler>
        print "Event handler `on_deselect_all' not implemented!"
        event.Skip()

    def on_add_metabolite(self, event):  # wxGlade: MyDialog.<event_handler>
        print "Event handler `on_add_metabolite' not implemented!"
        event.Skip()

    def on_remove_selected(self, event):  # wxGlade: MyDialog.<event_handler>
        print "Event handler `on_remove_selected' not implemented!"
        event.Skip()

# end of class MyDialog
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = MyDialog(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
