language: python
sudo: false
python: 2.7
install:
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg --setuptools-version=18.7.1
    - bin/buildout -N -t 3 -c travis.cfg
script: bin/test
cache:
    directories:
        - buildout-cache/eggs
