general_parameters = \
    {'System': '\'Lilas\'',
     'Laser_Pointing_Angle': 0,
     'Molecular_Calc': 0,  # Use US standard atmosphere
     'Latitude_degrees_north': 50.63,
     'Longitude_degrees_east': 3.07,
     'Altitude_meter_asl': 0.4,
     'Call sign': 'mb',}

channel_parameters = \
    {'00355.p_an': {'channel_ID': 41,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0,},
     '00355.p_ph': {'channel_ID': 42,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0,},
     '00355.s_an': {'channel_ID': 41,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0.88,},
     '00355.s_ph': {'channel_ID': 42,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0.88},
     '00530.o_an': {'channel_ID': 43,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0,},
     '00530.o_ph': {'channel_ID': 44,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0,},
     '00532.p_an': {'channel_ID': 43,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0,},
     '00532.p_ph': {'channel_ID': 44,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0,},
     '00532.s_an': {'channel_ID': 43,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0.77,},
     '00532.s_ph': {'channel_ID': 44,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0.77,},
     '01064.o_an': {'channel_ID': 45,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0,},
     '00387.o_an': {'channel_ID': 45,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0,
                    'Depolarization_Factor': 0,},
     '00387.o_ph': {'channel_ID': 46,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0,},
     '00408.o_ph': {'channel_ID': 444,
                    'Background_Low': 19000,
                    'Background_High': 20000,
                    'Laser_Shots': 1000,
                    'LR_Input': 1,
                    'DAQ_Range': 0,
                    'Depolarization_Factor': 0,},
     }
