general_parameters =  \
{'System': '\'PEARL\'',
 'Laser_Pointing_Angle': 0,
 'Molecular_Calc': 0,
 'Latitude_degrees_north': 40.601039,
 'Longitude_degrees_east': 15.723771,
 'Altitude_meter_asl': 760.0} # This should be float

channel_parameters = \
{'355HR': {'channel_ID': 8,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '355LR': {'channel_ID': 14,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '386HR': {'channel_ID': 9,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '386LR': {'channel_ID': 15,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '407HR': {'channel_ID': 17,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '532HR': {'channel_ID': 7,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '532LR': {'channel_ID': 13,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '532SHR': {'channel_ID': 12,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '532PHR': {'channel_ID': 11,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '607HR': {'channel_ID': 10,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 3000,
         'LR_Input':1,
         'DAQ_Range':0,
         'Depolarization_Factor': 0,},
 '1064': {'channel_ID': 6,
         'Background_Low': 30000,
         'Background_High': 50000,
         'Laser_Shots': 1500,
         'LR_Input':1,
         'DAQ_Range':100,
         'Depolarization_Factor': 0,},
        
         }

#For testing. To be read from milos files.
'''
measurement_parameters = \
{'Pressure_at_Lidar_Station': 930,
 'Temperature_at_Lidar_Station': 15,
 'Measurement_ID': '12345'}
'''


