# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Body8(object):

    """Implementation of the 'body_8' model.

    TODO: type model description here.

    Attributes:
        phone_number (string): A valid Ytel comma separated numbers (E.164
            format).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "phone_number":'PhoneNumber'
    }

    def __init__(self,
                 phone_number=None):
        """Constructor for the Body8 class"""

        # Initialize members of the class
        self.phone_number = phone_number


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        phone_number = dictionary.get('PhoneNumber')

        # Return an object of this model
        return cls(phone_number)


