# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Body4(object):

    """Implementation of the 'body_4' model.

    TODO: type model description here.

    Attributes:
        page (int): The page count to retrieve from the total results in the
            collection. Page indexing starts at 1.
        page_size (int): The count of objects to return per page.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page":'Page',
        "page_size":'PageSize'
    }

    def __init__(self,
                 page=None,
                 page_size=None):
        """Constructor for the Body4 class"""

        # Initialize members of the class
        self.page = page
        self.page_size = page_size


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        page = dictionary.get('Page')
        page_size = dictionary.get('PageSize')

        # Return an object of this model
        return cls(page,
                   page_size)


