# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Body11(object):

    """Implementation of the 'body_11' model.

    TODO: type model description here.

    Attributes:
        audiourl (string): URL pointing to the location of the audio file that
            is to be transcribed.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "audiourl":'audiourl'
    }

    def __init__(self,
                 audiourl=None):
        """Constructor for the Body11 class"""

        # Initialize members of the class
        self.audiourl = audiourl


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        audiourl = dictionary.get('audiourl')

        # Return an object of this model
        return cls(audiourl)


