# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class Direction1Enum(object):

    """Implementation of the 'Direction1' enum.

    The leg of the call audio will be played to

    Attributes:
        IN: TODO: type description here.
        OUT: TODO: type description here.
        BOTH: TODO: type description here.

    """

    ENUM_IN = 'in'

    OUT = 'out'

    BOTH = 'both'

