# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class GroupConfirmFileEnum(object):

    """Implementation of the 'GroupConfirmFile' enum.

    Specify the audio file you want to play when the called party picks up the
    call

    Attributes:
        MP3: TODO: type description here.
        WAV: TODO: type description here.

    """

    MP3 = 'mp3'

    WAV = 'wav'

