# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class NumberTypeEnum(object):

    """Implementation of the 'NumberType' enum.

    The capability supported by the number.Number type either SMS,Voice or
    all

    Attributes:
        ALL: TODO: type description here.
        VOICE: TODO: type description here.
        SMS: TODO: type description here.

    """

    ALL = 'all'

    VOICE = 'voice'

    SMS = 'sms'

