
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-13T13:14:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "86c6caa36f92a856b6cbbbbad3c2f5ad0e2efc77",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
