sudo: false
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
install:
  - pip install flake8
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - flake8
  - python setup.py test
after_success:
  - coveralls
