
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-01T11:21:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "34c149ad113164c0101dd3ec6e3c9add41c35a3e",
 "version": "v2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
