
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-18T11:27:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3edf27c49225b129b037263ac93cae5a440f1ae2",
 "version": "0.11.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
