# Generated by Django 2.1.3 on 2018-11-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cindy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfeed',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFeed',
        ),
    ]
