[tool.poetry]
name = "tmobile-call-log"
version = "0.1.0"
description = "Creates plots from T-Mobile personal call logs."
authors = ["Manny Ochoa <dev@manuelochoa.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.23.4"
numpy = "^1.15"
matplotlib = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
