#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mailspoof']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['mailspoof = mailspoof:main']}

setup(name='mailspoof',
      version='0.1.0',
      description='Scans SPF and DMARC records for issues that could allow email spoofing.',
      author='Alex Kaskasoli',
      author_email='alexkaskasoli@hotmail.com',
      url='https://alex.kaskaso.li/',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
