
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-01T11:30:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a1bf5a17007da529dfdb9021f90c107daef4cac",
 "version": "2018.12.01.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
