# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem_registration', '0005_auto_20181112_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='bill_address_optional',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес доставки доп.'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='bill_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город доставки'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='bill_country',
            field=models.ForeignKey(blank=True, help_text='Страна доставки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_countries', to='cities_light.Country', verbose_name='Страна доставки'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='bill_zip',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Почтовый индекс доставки'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='billing_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес доставки'),
        ),
    ]
