# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2018-11-16 00:55:11 UTC
from __future__ import unicode_literals
import datetime

version = "3.1rc1"
githash = "4c05fe5b62186bf4a9df500474003441d806649b"


major = 3
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2018, 11, 16, 0, 55, 11)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
