[tool.poetry]
name = "howoldru"
version = "0.1.2"
description = ""
authors = ["kk6 <hiro.ashiya@gmail.com>"]
homepage = "https://github.com/kk6"

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.1.3"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
howoldru = "howoldru:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
