structure:
  architectures_dir: architectures
  models_dir: models
  losses_dir: losses
  metrics_dir: metrics
  datasets_dir: datasets
  products_dir: products
  preprocessors_dir: preprocessors

configurations:
  model_specs: specs.yaml
  train_configs: train.yaml
  evaluator_config: evaluation.yaml
