
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-26T19:38:34-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "16f44b06aefa16d790f97ea6d1329ef872ec146a",
 "version": "0.9.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
