
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-18T12:38:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2d791223686295c9539b37967978234e2f45897",
 "version": "5.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
