checks:
  python:
    code_rating: true
    duplicate_code: true
    classes_valid_slots: true

build:
  environment:
    python: 3.6
    variables:
      TOXENV: py36,report
  nodes:
    analysis:
      project_setup:
        override:
          - "true"
      tests:
        override:
          - py-scrutinizer-run
    tests: true
filter:
  excluded_paths:
    - "*/test/*"
  dependency_paths:
    - "lib/*"
tools:
  external_code_coverage:
    # py27,py34,py35,py36,py37
    runs: 5
    # timeout in seconds, default 5 minutes
    timeout: 300
