# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'deleted', b'Deleted'), (b'completed', b'Completed'), (b'waiting', b'Waiting'), (b'recurring', b'Recurring')], default=b'pending', max_length=9)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entry', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('scheduled', models.DateTimeField(blank=True, null=True)),
                ('wait', models.DateTimeField(blank=True, null=True)),
                ('recur', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[(b'H', b'High'), (b'M', b'Medium'), (b'L', b'Low')], default=None, max_length=1, null=True)),
                ('depends', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testannotation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskdj.TestTask'),
        ),
    ]
