# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskdj', '0004_auto_20160719_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testannotation',
            name='task',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TestTaskNoRelations',
        ),
        migrations.DeleteModel(
            name='TestAnnotation',
        ),
        migrations.DeleteModel(
            name='TestTag',
        ),
        migrations.DeleteModel(
            name='TestTask',
        ),
    ]
