environment:
  matrix:
    - PYTHON_VERSION: 3.5
      PYTHON_BUILD: 35
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
      PYTHON_BUILD: 36

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

cache:
  - "%QUEST_CACHE_DIR%"

platform:
  - x64

build: false


install:
  # Install miniconda using a powershell script.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - ps: "(Get-Content conda_environment.yml).replace('python=3', \"python=$env:PYTHON_VERSION\") | Set-Content conda_environment.yml"
  - conda env create -q -n test-environment -f conda_environment.yml
  - activate test-environment
  - python setup.py install
# the following line installs a specific build of pytables. It will hopefully not be necessary on the next release
  - "conda install -c conda-forge pytables=3.4.4=py%PYTHON_BUILD%h7e76658_1"
  - conda list
  - python -c "import quest; quest.api.update_settings(dict(CACHE_DIR='%QUEST_CACHE_DIR%')); quest.api.save_settings()"

test_script:
  - python -m pytest -vv