version: '3'
services:
  redhat:
    build:
      context: $PWD
      dockerfile: Dockerfile-redhat
      args:
        - IMAGE=centos:7
        - UNAME=$USER
        # - UID=1000
        # - GID=1000
    image: niceman:redhat
    container_name: niceman-redhat
    volumes:
      - $PWD:/home/$USER/niceman
      - /var/run/docker.sock:/var/run/docker.sock
  debian:
    build:
      context: $PWD
      dockerfile: Dockerfile-debian
      args:
        - IMAGE=debian:jessie
        - UNAME=$USER
        # - UID=1000
        # - GID=1000
    image: niceman:debian
    container_name: niceman-debian
    volumes:
      - $PWD:/home/$USER/niceman
      - /var/run/docker.sock:/var/run/docker.sock