stages:
  - build
  - test
  - deploy
  - documentation

test:
  stage: test
  script:
    - env PYTHONPATH=. pytest-3 -v .


style check:
  stage: test
  script:
    - pycodestyle
  allow_failure: true


type check:
  stage: test
  script:
    - mypy --package ${CI_PROJECT_NAME//-/.}
  allow_failure: true


create deb package:
  stage: deploy
  only:
    - tags
  script:
    - python3 setup.py --command-packages=stdeb.command sdist_dsc --with-python2=False --with-python3=True bdist_deb
  artifacts:
    paths:
      - deb_dist/python3-${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME:1}-1_all.deb


create wheel package:
  stage: deploy
  only:
    - tags
  script:
    - pip3 wheel .
  artifacts:
    paths:
      - '${CI_PROJECT_NAME//-/_}-${CI_COMMIT_REF_NAME:1}-py3-none-any.whl'


create tarball:
  stage: deploy
  only:
    - tags
  script:
    - git archive --format=tar.gz ${CI_COMMIT_REF_NAME} --prefix=${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME:1}/ --output ${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME:1}.tar.gz
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME:1}.tar.gz


create html documentation:
  stage: documentation
  only:
    - tags
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html/


create man pages:
  stage: documentation
  only:
    - tags
  script:
    - cd docs
    - make man
  artifacts:
    paths:
      - docs/build/man/
