# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_boxberry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsel',
            name='track',
            field=models.CharField(blank=True, help_text='Если параметр будет не пустым, считается что вы хотите обновить ранее созданную посылку', max_length=15, null=True, verbose_name='Трекинг код'),
        ),
    ]
