
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-04T14:08:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1c470d9a687637091b98cf20abe5ed47baa2784",
 "version": "0.8.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
