stages:
  - install
  - unittest
  - totaltest
  - deploy

#########################################
###### Installing all dependencies ######
#########################################
inst:
    stage: install
    script:
        - python3 -m pip install --user requests


#########################################
##### Testing for single components #####
#########################################

unit:
    stage: unittest
    script:
        - python3 -m unittest discover .

#########################################
###### Testing of the whole system ######
#########################################
linter:
    stage: totaltest
    before_script:
      - python3 -m pip install --user prospector[with_everything]
    script:
      - echo "Running linter for project"
      - ~/.local/bin/prospector


#########################################
############# Deployment ################
#########################################

pypi:
  stage: deploy
  before_script:
    - python3 -m pip install --user --upgrade twine setuptools wheel
  script:
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload dist/*
  only:
    - tags
    - triggers
