---
language: python

python:
    - "2.7"

install:
    - pip install --process-dependency-links ./
    - pip install coveralls

script:
    - coverage run -m unittest discover ./test/unit -v

after_success:
    - coveralls