[build-system]
requires = ["setuptools", "wheel"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pyntc"
author = "Network to Code"
author-email = "ntc@networktocode.com"
home-page = "https://github.com/networktocode/pyntc"
description-file = "README.md"
requires = [
    "requests>=2.7.0",
    "jsonschema",
    "future",
    "netmiko",
    "paramiko",
    "pynxos>=0.0.3",
    "coverage",
    "mock>=1.3",
    "textfsm",
    "terminal",
    "f5-sdk",
    "bigsuds",
    "pyeapi",
    "junos-eznc",
    "scp",
]

[tool.black]
line-length = 120
py36 = true
include = '\.pyi?$'
exclude = '''
/(
  \.git
| \.tox
| \.venv
| _build
| buck-out
| build
| dist
| blib2to3
| tests/data
)/
'''
