[tool.poetry]
name = "slackperson"
version = "0.1.0"
description = ""
authors = ["Rick Henry <fredericmhenry@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
attrs = "^18.2"
nameparser = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
