# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:20
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_self_publish', '0002_auto_20161016_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationrecord',
            name='concept',
            field=aristotle_mdr.fields.ConceptOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicationrecord', to='aristotle_mdr._concept'),
        ),
    ]
