# -*- coding: utf-8 -*-
"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = http://en.wikipedia.beta.wmflabs.org/
  name = wpbeta

Please do not commit this to the Git repository!
"""
from __future__ import absolute_import, division, unicode_literals

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):  # noqa: D101

    name = 'wpbeta'
    langs = {
        'en': 'en.wikipedia.beta.wmflabs.org',
        'aa': 'aa.wikipedia.beta.wmflabs.org',
        'ar': 'ar.wikipedia.beta.wmflabs.org',
        'ca': 'ca.wikipedia.beta.wmflabs.org',
        'crh': 'crh.wikipedia.beta.wmflabs.org',
        'de': 'de.wikipedia.beta.wmflabs.org',
        'en-rtl': 'en-rtl.wikipedia.beta.wmflabs.org',
        'eo': 'eo.wikipedia.beta.wmflabs.org',
        'es': 'es.wikipedia.beta.wmflabs.org',
        'fa': 'fa.wikipedia.beta.wmflabs.org',
        'he': 'he.wikipedia.beta.wmflabs.org',
        'hi': 'hi.wikipedia.beta.wmflabs.org',
        'ja': 'ja.wikipedia.beta.wmflabs.org',
        'ko': 'ko.wikipedia.beta.wmflabs.org',
        'nl': 'nl.wikipedia.beta.wmflabs.org',
        'ru': 'ru.wikipedia.beta.wmflabs.org',
        'simple': 'simple.wikipedia.beta.wmflabs.org',
        'sq': 'sq.wikipedia.beta.wmflabs.org',
        'sr': 'sr.wikipedia.beta.wmflabs.org',
        'uk': 'uk.wikipedia.beta.wmflabs.org',
        'zh': 'zh.wikipedia.beta.wmflabs.org',
    }

    def scriptpath(self, code):
        return {
            'en': '/w',
            'aa': '/w',
            'ar': '/w',
            'ca': '/w',
            'crh': '/w',
            'de': '/w',
            'en-rtl': '/w',
            'eo': '/w',
            'es': '/w',
            'fa': '/w',
            'he': '/w',
            'hi': '/w',
            'ja': '/w',
            'ko': '/w',
            'nl': '/w',
            'ru': '/w',
            'simple': '/w',
            'sq': '/w',
            'sr': '/w',
            'uk': '/w',
            'zh': '/w',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': '1.33.0-alpha',
            'aa': '1.33.0-alpha',
            'ar': '1.33.0-alpha',
            'ca': '1.33.0-alpha',
            'crh': '1.33.0-alpha',
            'de': '1.33.0-alpha',
            'en-rtl': '1.33.0-alpha',
            'eo': '1.33.0-alpha',
            'es': '1.33.0-alpha',
            'fa': '1.33.0-alpha',
            'he': '1.33.0-alpha',
            'hi': '1.33.0-alpha',
            'ja': '1.33.0-alpha',
            'ko': '1.33.0-alpha',
            'nl': '1.33.0-alpha',
            'ru': '1.33.0-alpha',
            'simple': '1.33.0-alpha',
            'sq': '1.33.0-alpha',
            'sr': '1.33.0-alpha',
            'uk': '1.33.0-alpha',
            'zh': '1.33.0-alpha',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
            'aa': 'https',
            'ar': 'https',
            'ca': 'https',
            'crh': 'https',
            'de': 'https',
            'en-rtl': 'https',
            'eo': 'https',
            'es': 'https',
            'fa': 'https',
            'he': 'https',
            'hi': 'https',
            'ja': 'https',
            'ko': 'https',
            'nl': 'https',
            'ru': 'https',
            'simple': 'https',
            'sq': 'https',
            'sr': 'https',
            'uk': 'https',
            'zh': 'https',
        }[code]
