
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "54e2596d9f370609013a69680e940dbb161528f5",
 "version": "0.4.2.b3176"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
