
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-07T18:42:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "db46a736953cb17c178bd1e7e48b87dea070c214",
 "version": "0.1.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
