language: python
sudo: false
dist: trusty

python:
  - "3.5"
  - "3.6"

cache:
    apt: true
    pip: true
    ccache: true

before_install:
    # install miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"

    # update miniconda
    - conda config --set always_yes yes
    - conda update -q conda
    - conda config --add channels conda-forge

    # create and activate env
    - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment


install:
    - pip install -U setuptools pip wheel codecov
    - pip install PyQt5==5.9.2
    - source $TRAVIS_BUILD_DIR/.travis/install_orange3.sh
    # - pip install Orange3 -> not installing orange correctly, why?
    - pip install -e .

script:
    - catchsegv xvfb-run -a -s "-screen 0 1280x1024x24" coverage run setup.py test

after_success:
- codecov
