# Performance Output Parameters types
TYPE_DEFAULT = 'DEFAULT'
TYPE_TRAINED_MODEL = 'TRAINED_MODEL'
TYPE_RESULT_MATRIX = 'RESULT_MATRIX'
TYPE_ANALYSIS_RESULT = 'ANALYSIS_RESULT'
TYPE_RESULT_DATASET = 'RESULT_DATASET'

# Analysis types
ANALYSIS_TYPE_BATCH = 'batch'
ANALYSIS_TYPE_ITERATIVE = 'iterative'
