- name: Creating uWSGI configuration file...
  vars:
    uwsgi_pid_file: '{{ control_server_configuration.uwsgi_pid_file }}'
  template:
    src: ../../../configuration/templates/uwsgi.ini.j2
    dest: '{{ control_server_configuration.uwsgi_configuration_file }}'
