# -*- coding: utf-8 -*-

"""
    YtelAPI

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from YtelAPI.api_helper import APIHelper


class CarrierControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(CarrierControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.carrier

    # Retrieve a list of carrier lookup objects.
    def test_test_carrier_results(self):
        # Parameters for the API call
        page = None
        page_size = None

        # Perform the API call through the SDK function
        result = self.controller.create_carrier_results(page, page_size)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


