
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5b322f7c2b82a502b1e1b70703ae45f1f668d07d",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
