
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-13T16:17:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "71278291badca00d3514f6c3a9177502fc64f1f5",
 "version": "3.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
