// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nucleus/protos/gff.proto

#ifndef PROTOBUF_INCLUDED_nucleus_2fprotos_2fgff_2eproto
#define PROTOBUF_INCLUDED_nucleus_2fprotos_2fgff_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "nucleus/protos/range.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_nucleus_2fprotos_2fgff_2eproto 

namespace protobuf_nucleus_2fprotos_2fgff_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_nucleus_2fprotos_2fgff_2eproto
namespace nucleus {
namespace genomics {
namespace v1 {
class GffHeader;
class GffHeaderDefaultTypeInternal;
extern GffHeaderDefaultTypeInternal _GffHeader_default_instance_;
class GffHeader_GenomeBuildDirective;
class GffHeader_GenomeBuildDirectiveDefaultTypeInternal;
extern GffHeader_GenomeBuildDirectiveDefaultTypeInternal _GffHeader_GenomeBuildDirective_default_instance_;
class GffHeader_OntologyDirective;
class GffHeader_OntologyDirectiveDefaultTypeInternal;
extern GffHeader_OntologyDirectiveDefaultTypeInternal _GffHeader_OntologyDirective_default_instance_;
class GffReaderOptions;
class GffReaderOptionsDefaultTypeInternal;
extern GffReaderOptionsDefaultTypeInternal _GffReaderOptions_default_instance_;
class GffRecord;
class GffRecordDefaultTypeInternal;
extern GffRecordDefaultTypeInternal _GffRecord_default_instance_;
class GffRecord_AttributesEntry_DoNotUse;
class GffRecord_AttributesEntry_DoNotUseDefaultTypeInternal;
extern GffRecord_AttributesEntry_DoNotUseDefaultTypeInternal _GffRecord_AttributesEntry_DoNotUse_default_instance_;
class GffWriterOptions;
class GffWriterOptionsDefaultTypeInternal;
extern GffWriterOptionsDefaultTypeInternal _GffWriterOptions_default_instance_;
}  // namespace v1
}  // namespace genomics
}  // namespace nucleus
namespace google {
namespace protobuf {
template<> ::nucleus::genomics::v1::GffHeader* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffHeader>(Arena*);
template<> ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffHeader_GenomeBuildDirective>(Arena*);
template<> ::nucleus::genomics::v1::GffHeader_OntologyDirective* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffHeader_OntologyDirective>(Arena*);
template<> ::nucleus::genomics::v1::GffReaderOptions* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffReaderOptions>(Arena*);
template<> ::nucleus::genomics::v1::GffRecord* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffRecord>(Arena*);
template<> ::nucleus::genomics::v1::GffRecord_AttributesEntry_DoNotUse* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffRecord_AttributesEntry_DoNotUse>(Arena*);
template<> ::nucleus::genomics::v1::GffWriterOptions* Arena::CreateMaybeMessage<::nucleus::genomics::v1::GffWriterOptions>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace nucleus {
namespace genomics {
namespace v1 {

enum GffRecord_Strand {
  GffRecord_Strand_UNSPECIFIED_STRAND = 0,
  GffRecord_Strand_FORWARD_STRAND = 1,
  GffRecord_Strand_REVERSE_STRAND = 2,
  GffRecord_Strand_GffRecord_Strand_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GffRecord_Strand_GffRecord_Strand_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GffRecord_Strand_IsValid(int value);
const GffRecord_Strand GffRecord_Strand_Strand_MIN = GffRecord_Strand_UNSPECIFIED_STRAND;
const GffRecord_Strand GffRecord_Strand_Strand_MAX = GffRecord_Strand_REVERSE_STRAND;
const int GffRecord_Strand_Strand_ARRAYSIZE = GffRecord_Strand_Strand_MAX + 1;

const ::google::protobuf::EnumDescriptor* GffRecord_Strand_descriptor();
inline const ::std::string& GffRecord_Strand_Name(GffRecord_Strand value) {
  return ::google::protobuf::internal::NameOfEnum(
    GffRecord_Strand_descriptor(), value);
}
inline bool GffRecord_Strand_Parse(
    const ::std::string& name, GffRecord_Strand* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GffRecord_Strand>(
    GffRecord_Strand_descriptor(), name, value);
}
// ===================================================================

class GffRecord_AttributesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<GffRecord_AttributesEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<GffRecord_AttributesEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  GffRecord_AttributesEntry_DoNotUse();
  GffRecord_AttributesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const GffRecord_AttributesEntry_DoNotUse& other);
  static const GffRecord_AttributesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const GffRecord_AttributesEntry_DoNotUse*>(&_GffRecord_AttributesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class GffRecord : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.GffRecord) */ {
 public:
  GffRecord();
  virtual ~GffRecord();

  GffRecord(const GffRecord& from);

  inline GffRecord& operator=(const GffRecord& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GffRecord(GffRecord&& from) noexcept
    : GffRecord() {
    *this = ::std::move(from);
  }

  inline GffRecord& operator=(GffRecord&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GffRecord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GffRecord* internal_default_instance() {
    return reinterpret_cast<const GffRecord*>(
               &_GffRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GffRecord* other);
  friend void swap(GffRecord& a, GffRecord& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GffRecord* New() const final {
    return CreateMaybeMessage<GffRecord>(NULL);
  }

  GffRecord* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GffRecord>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GffRecord& from);
  void MergeFrom(const GffRecord& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GffRecord* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  typedef GffRecord_Strand Strand;
  static const Strand UNSPECIFIED_STRAND =
    GffRecord_Strand_UNSPECIFIED_STRAND;
  static const Strand FORWARD_STRAND =
    GffRecord_Strand_FORWARD_STRAND;
  static const Strand REVERSE_STRAND =
    GffRecord_Strand_REVERSE_STRAND;
  static inline bool Strand_IsValid(int value) {
    return GffRecord_Strand_IsValid(value);
  }
  static const Strand Strand_MIN =
    GffRecord_Strand_Strand_MIN;
  static const Strand Strand_MAX =
    GffRecord_Strand_Strand_MAX;
  static const int Strand_ARRAYSIZE =
    GffRecord_Strand_Strand_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Strand_descriptor() {
    return GffRecord_Strand_descriptor();
  }
  static inline const ::std::string& Strand_Name(Strand value) {
    return GffRecord_Strand_Name(value);
  }
  static inline bool Strand_Parse(const ::std::string& name,
      Strand* value) {
    return GffRecord_Strand_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // map<string, string> attributes = 7;
  int attributes_size() const;
  void clear_attributes();
  static const int kAttributesFieldNumber = 7;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      attributes() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_attributes();

  // string source = 2;
  void clear_source();
  static const int kSourceFieldNumber = 2;
  const ::std::string& source() const;
  void set_source(const ::std::string& value);
  #if LANG_CXX11
  void set_source(::std::string&& value);
  #endif
  void set_source(const char* value);
  void set_source(const char* value, size_t size);
  ::std::string* mutable_source();
  ::std::string* release_source();
  void set_allocated_source(::std::string* source);

  // string type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // .nucleus.genomics.v1.Range range = 1;
  bool has_range() const;
  void clear_range();
  static const int kRangeFieldNumber = 1;
  private:
  const ::nucleus::genomics::v1::Range& _internal_range() const;
  public:
  const ::nucleus::genomics::v1::Range& range() const;
  ::nucleus::genomics::v1::Range* release_range();
  ::nucleus::genomics::v1::Range* mutable_range();
  void set_allocated_range(::nucleus::genomics::v1::Range* range);

  // double score = 4;
  void clear_score();
  static const int kScoreFieldNumber = 4;
  double score() const;
  void set_score(double value);

  // .nucleus.genomics.v1.GffRecord.Strand strand = 5;
  void clear_strand();
  static const int kStrandFieldNumber = 5;
  ::nucleus::genomics::v1::GffRecord_Strand strand() const;
  void set_strand(::nucleus::genomics::v1::GffRecord_Strand value);

  // int32 phase = 6;
  void clear_phase();
  static const int kPhaseFieldNumber = 6;
  ::google::protobuf::int32 phase() const;
  void set_phase(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.GffRecord)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      GffRecord_AttributesEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > attributes_;
  ::google::protobuf::internal::ArenaStringPtr source_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::nucleus::genomics::v1::Range* range_;
  double score_;
  int strand_;
  ::google::protobuf::int32 phase_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2fgff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GffHeader_OntologyDirective : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.GffHeader.OntologyDirective) */ {
 public:
  GffHeader_OntologyDirective();
  virtual ~GffHeader_OntologyDirective();

  GffHeader_OntologyDirective(const GffHeader_OntologyDirective& from);

  inline GffHeader_OntologyDirective& operator=(const GffHeader_OntologyDirective& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GffHeader_OntologyDirective(GffHeader_OntologyDirective&& from) noexcept
    : GffHeader_OntologyDirective() {
    *this = ::std::move(from);
  }

  inline GffHeader_OntologyDirective& operator=(GffHeader_OntologyDirective&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GffHeader_OntologyDirective& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GffHeader_OntologyDirective* internal_default_instance() {
    return reinterpret_cast<const GffHeader_OntologyDirective*>(
               &_GffHeader_OntologyDirective_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GffHeader_OntologyDirective* other);
  friend void swap(GffHeader_OntologyDirective& a, GffHeader_OntologyDirective& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GffHeader_OntologyDirective* New() const final {
    return CreateMaybeMessage<GffHeader_OntologyDirective>(NULL);
  }

  GffHeader_OntologyDirective* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GffHeader_OntologyDirective>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GffHeader_OntologyDirective& from);
  void MergeFrom(const GffHeader_OntologyDirective& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GffHeader_OntologyDirective* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string uri = 1;
  void clear_uri();
  static const int kUriFieldNumber = 1;
  const ::std::string& uri() const;
  void set_uri(const ::std::string& value);
  #if LANG_CXX11
  void set_uri(::std::string&& value);
  #endif
  void set_uri(const char* value);
  void set_uri(const char* value, size_t size);
  ::std::string* mutable_uri();
  ::std::string* release_uri();
  void set_allocated_uri(::std::string* uri);

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.GffHeader.OntologyDirective)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr uri_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2fgff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GffHeader_GenomeBuildDirective : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.GffHeader.GenomeBuildDirective) */ {
 public:
  GffHeader_GenomeBuildDirective();
  virtual ~GffHeader_GenomeBuildDirective();

  GffHeader_GenomeBuildDirective(const GffHeader_GenomeBuildDirective& from);

  inline GffHeader_GenomeBuildDirective& operator=(const GffHeader_GenomeBuildDirective& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GffHeader_GenomeBuildDirective(GffHeader_GenomeBuildDirective&& from) noexcept
    : GffHeader_GenomeBuildDirective() {
    *this = ::std::move(from);
  }

  inline GffHeader_GenomeBuildDirective& operator=(GffHeader_GenomeBuildDirective&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GffHeader_GenomeBuildDirective& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GffHeader_GenomeBuildDirective* internal_default_instance() {
    return reinterpret_cast<const GffHeader_GenomeBuildDirective*>(
               &_GffHeader_GenomeBuildDirective_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GffHeader_GenomeBuildDirective* other);
  friend void swap(GffHeader_GenomeBuildDirective& a, GffHeader_GenomeBuildDirective& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GffHeader_GenomeBuildDirective* New() const final {
    return CreateMaybeMessage<GffHeader_GenomeBuildDirective>(NULL);
  }

  GffHeader_GenomeBuildDirective* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GffHeader_GenomeBuildDirective>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GffHeader_GenomeBuildDirective& from);
  void MergeFrom(const GffHeader_GenomeBuildDirective& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GffHeader_GenomeBuildDirective* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string source = 1;
  void clear_source();
  static const int kSourceFieldNumber = 1;
  const ::std::string& source() const;
  void set_source(const ::std::string& value);
  #if LANG_CXX11
  void set_source(::std::string&& value);
  #endif
  void set_source(const char* value);
  void set_source(const char* value, size_t size);
  ::std::string* mutable_source();
  ::std::string* release_source();
  void set_allocated_source(::std::string* source);

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.GffHeader.GenomeBuildDirective)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr source_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2fgff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GffHeader : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.GffHeader) */ {
 public:
  GffHeader();
  virtual ~GffHeader();

  GffHeader(const GffHeader& from);

  inline GffHeader& operator=(const GffHeader& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GffHeader(GffHeader&& from) noexcept
    : GffHeader() {
    *this = ::std::move(from);
  }

  inline GffHeader& operator=(GffHeader&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GffHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GffHeader* internal_default_instance() {
    return reinterpret_cast<const GffHeader*>(
               &_GffHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(GffHeader* other);
  friend void swap(GffHeader& a, GffHeader& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GffHeader* New() const final {
    return CreateMaybeMessage<GffHeader>(NULL);
  }

  GffHeader* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GffHeader>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GffHeader& from);
  void MergeFrom(const GffHeader& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GffHeader* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GffHeader_OntologyDirective OntologyDirective;
  typedef GffHeader_GenomeBuildDirective GenomeBuildDirective;

  // accessors -------------------------------------------------------

  // repeated .nucleus.genomics.v1.Range sequence_regions = 2;
  int sequence_regions_size() const;
  void clear_sequence_regions();
  static const int kSequenceRegionsFieldNumber = 2;
  ::nucleus::genomics::v1::Range* mutable_sequence_regions(int index);
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::Range >*
      mutable_sequence_regions();
  const ::nucleus::genomics::v1::Range& sequence_regions(int index) const;
  ::nucleus::genomics::v1::Range* add_sequence_regions();
  const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::Range >&
      sequence_regions() const;

  // repeated .nucleus.genomics.v1.GffHeader.OntologyDirective feature_ontologies = 3;
  int feature_ontologies_size() const;
  void clear_feature_ontologies();
  static const int kFeatureOntologiesFieldNumber = 3;
  ::nucleus::genomics::v1::GffHeader_OntologyDirective* mutable_feature_ontologies(int index);
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >*
      mutable_feature_ontologies();
  const ::nucleus::genomics::v1::GffHeader_OntologyDirective& feature_ontologies(int index) const;
  ::nucleus::genomics::v1::GffHeader_OntologyDirective* add_feature_ontologies();
  const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >&
      feature_ontologies() const;

  // repeated .nucleus.genomics.v1.GffHeader.OntologyDirective attribute_ontologies = 4;
  int attribute_ontologies_size() const;
  void clear_attribute_ontologies();
  static const int kAttributeOntologiesFieldNumber = 4;
  ::nucleus::genomics::v1::GffHeader_OntologyDirective* mutable_attribute_ontologies(int index);
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >*
      mutable_attribute_ontologies();
  const ::nucleus::genomics::v1::GffHeader_OntologyDirective& attribute_ontologies(int index) const;
  ::nucleus::genomics::v1::GffHeader_OntologyDirective* add_attribute_ontologies();
  const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >&
      attribute_ontologies() const;

  // repeated .nucleus.genomics.v1.GffHeader.OntologyDirective source_ontologies = 5;
  int source_ontologies_size() const;
  void clear_source_ontologies();
  static const int kSourceOntologiesFieldNumber = 5;
  ::nucleus::genomics::v1::GffHeader_OntologyDirective* mutable_source_ontologies(int index);
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >*
      mutable_source_ontologies();
  const ::nucleus::genomics::v1::GffHeader_OntologyDirective& source_ontologies(int index) const;
  ::nucleus::genomics::v1::GffHeader_OntologyDirective* add_source_ontologies();
  const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >&
      source_ontologies() const;

  // string gff_version = 1;
  void clear_gff_version();
  static const int kGffVersionFieldNumber = 1;
  const ::std::string& gff_version() const;
  void set_gff_version(const ::std::string& value);
  #if LANG_CXX11
  void set_gff_version(::std::string&& value);
  #endif
  void set_gff_version(const char* value);
  void set_gff_version(const char* value, size_t size);
  ::std::string* mutable_gff_version();
  ::std::string* release_gff_version();
  void set_allocated_gff_version(::std::string* gff_version);

  // string species = 6;
  void clear_species();
  static const int kSpeciesFieldNumber = 6;
  const ::std::string& species() const;
  void set_species(const ::std::string& value);
  #if LANG_CXX11
  void set_species(::std::string&& value);
  #endif
  void set_species(const char* value);
  void set_species(const char* value, size_t size);
  ::std::string* mutable_species();
  ::std::string* release_species();
  void set_allocated_species(::std::string* species);

  // .nucleus.genomics.v1.GffHeader.GenomeBuildDirective genome_build = 7;
  bool has_genome_build() const;
  void clear_genome_build();
  static const int kGenomeBuildFieldNumber = 7;
  private:
  const ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective& _internal_genome_build() const;
  public:
  const ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective& genome_build() const;
  ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* release_genome_build();
  ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* mutable_genome_build();
  void set_allocated_genome_build(::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* genome_build);

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.GffHeader)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::Range > sequence_regions_;
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective > feature_ontologies_;
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective > attribute_ontologies_;
  ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective > source_ontologies_;
  ::google::protobuf::internal::ArenaStringPtr gff_version_;
  ::google::protobuf::internal::ArenaStringPtr species_;
  ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* genome_build_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2fgff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GffReaderOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.GffReaderOptions) */ {
 public:
  GffReaderOptions();
  virtual ~GffReaderOptions();

  GffReaderOptions(const GffReaderOptions& from);

  inline GffReaderOptions& operator=(const GffReaderOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GffReaderOptions(GffReaderOptions&& from) noexcept
    : GffReaderOptions() {
    *this = ::std::move(from);
  }

  inline GffReaderOptions& operator=(GffReaderOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GffReaderOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GffReaderOptions* internal_default_instance() {
    return reinterpret_cast<const GffReaderOptions*>(
               &_GffReaderOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(GffReaderOptions* other);
  friend void swap(GffReaderOptions& a, GffReaderOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GffReaderOptions* New() const final {
    return CreateMaybeMessage<GffReaderOptions>(NULL);
  }

  GffReaderOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GffReaderOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GffReaderOptions& from);
  void MergeFrom(const GffReaderOptions& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GffReaderOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.GffReaderOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2fgff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GffWriterOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nucleus.genomics.v1.GffWriterOptions) */ {
 public:
  GffWriterOptions();
  virtual ~GffWriterOptions();

  GffWriterOptions(const GffWriterOptions& from);

  inline GffWriterOptions& operator=(const GffWriterOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GffWriterOptions(GffWriterOptions&& from) noexcept
    : GffWriterOptions() {
    *this = ::std::move(from);
  }

  inline GffWriterOptions& operator=(GffWriterOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GffWriterOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GffWriterOptions* internal_default_instance() {
    return reinterpret_cast<const GffWriterOptions*>(
               &_GffWriterOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(GffWriterOptions* other);
  friend void swap(GffWriterOptions& a, GffWriterOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GffWriterOptions* New() const final {
    return CreateMaybeMessage<GffWriterOptions>(NULL);
  }

  GffWriterOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GffWriterOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GffWriterOptions& from);
  void MergeFrom(const GffWriterOptions& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GffWriterOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:nucleus.genomics.v1.GffWriterOptions)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_nucleus_2fprotos_2fgff_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GffRecord

// .nucleus.genomics.v1.Range range = 1;
inline bool GffRecord::has_range() const {
  return this != internal_default_instance() && range_ != NULL;
}
inline const ::nucleus::genomics::v1::Range& GffRecord::_internal_range() const {
  return *range_;
}
inline const ::nucleus::genomics::v1::Range& GffRecord::range() const {
  const ::nucleus::genomics::v1::Range* p = range_;
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffRecord.range)
  return p != NULL ? *p : *reinterpret_cast<const ::nucleus::genomics::v1::Range*>(
      &::nucleus::genomics::v1::_Range_default_instance_);
}
inline ::nucleus::genomics::v1::Range* GffRecord::release_range() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffRecord.range)
  
  ::nucleus::genomics::v1::Range* temp = range_;
  range_ = NULL;
  return temp;
}
inline ::nucleus::genomics::v1::Range* GffRecord::mutable_range() {
  
  if (range_ == NULL) {
    auto* p = CreateMaybeMessage<::nucleus::genomics::v1::Range>(GetArenaNoVirtual());
    range_ = p;
  }
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffRecord.range)
  return range_;
}
inline void GffRecord::set_allocated_range(::nucleus::genomics::v1::Range* range) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(range_);
  }
  if (range) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(range)->GetArena();
    if (message_arena != submessage_arena) {
      range = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, range, submessage_arena);
    }
    
  } else {
    
  }
  range_ = range;
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffRecord.range)
}

// string source = 2;
inline void GffRecord::clear_source() {
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffRecord::source() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffRecord.source)
  return source_.GetNoArena();
}
inline void GffRecord::set_source(const ::std::string& value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffRecord.source)
}
#if LANG_CXX11
inline void GffRecord::set_source(::std::string&& value) {
  
  source_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffRecord.source)
}
#endif
inline void GffRecord::set_source(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffRecord.source)
}
inline void GffRecord::set_source(const char* value, size_t size) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffRecord.source)
}
inline ::std::string* GffRecord::mutable_source() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffRecord.source)
  return source_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffRecord::release_source() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffRecord.source)
  
  return source_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffRecord::set_allocated_source(::std::string* source) {
  if (source != NULL) {
    
  } else {
    
  }
  source_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffRecord.source)
}

// string type = 3;
inline void GffRecord::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffRecord::type() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffRecord.type)
  return type_.GetNoArena();
}
inline void GffRecord::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffRecord.type)
}
#if LANG_CXX11
inline void GffRecord::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffRecord.type)
}
#endif
inline void GffRecord::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffRecord.type)
}
inline void GffRecord::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffRecord.type)
}
inline ::std::string* GffRecord::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffRecord.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffRecord::release_type() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffRecord.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffRecord::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffRecord.type)
}

// double score = 4;
inline void GffRecord::clear_score() {
  score_ = 0;
}
inline double GffRecord::score() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffRecord.score)
  return score_;
}
inline void GffRecord::set_score(double value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffRecord.score)
}

// .nucleus.genomics.v1.GffRecord.Strand strand = 5;
inline void GffRecord::clear_strand() {
  strand_ = 0;
}
inline ::nucleus::genomics::v1::GffRecord_Strand GffRecord::strand() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffRecord.strand)
  return static_cast< ::nucleus::genomics::v1::GffRecord_Strand >(strand_);
}
inline void GffRecord::set_strand(::nucleus::genomics::v1::GffRecord_Strand value) {
  
  strand_ = value;
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffRecord.strand)
}

// int32 phase = 6;
inline void GffRecord::clear_phase() {
  phase_ = 0;
}
inline ::google::protobuf::int32 GffRecord::phase() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffRecord.phase)
  return phase_;
}
inline void GffRecord::set_phase(::google::protobuf::int32 value) {
  
  phase_ = value;
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffRecord.phase)
}

// map<string, string> attributes = 7;
inline int GffRecord::attributes_size() const {
  return attributes_.size();
}
inline void GffRecord::clear_attributes() {
  attributes_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
GffRecord::attributes() const {
  // @@protoc_insertion_point(field_map:nucleus.genomics.v1.GffRecord.attributes)
  return attributes_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
GffRecord::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_map:nucleus.genomics.v1.GffRecord.attributes)
  return attributes_.MutableMap();
}

// -------------------------------------------------------------------

// GffHeader_OntologyDirective

// string uri = 1;
inline void GffHeader_OntologyDirective::clear_uri() {
  uri_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffHeader_OntologyDirective::uri() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
  return uri_.GetNoArena();
}
inline void GffHeader_OntologyDirective::set_uri(const ::std::string& value) {
  
  uri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
}
#if LANG_CXX11
inline void GffHeader_OntologyDirective::set_uri(::std::string&& value) {
  
  uri_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
}
#endif
inline void GffHeader_OntologyDirective::set_uri(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  uri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
}
inline void GffHeader_OntologyDirective::set_uri(const char* value, size_t size) {
  
  uri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
}
inline ::std::string* GffHeader_OntologyDirective::mutable_uri() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
  return uri_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffHeader_OntologyDirective::release_uri() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
  
  return uri_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffHeader_OntologyDirective::set_allocated_uri(::std::string* uri) {
  if (uri != NULL) {
    
  } else {
    
  }
  uri_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uri);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffHeader.OntologyDirective.uri)
}

// -------------------------------------------------------------------

// GffHeader_GenomeBuildDirective

// string source = 1;
inline void GffHeader_GenomeBuildDirective::clear_source() {
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffHeader_GenomeBuildDirective::source() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
  return source_.GetNoArena();
}
inline void GffHeader_GenomeBuildDirective::set_source(const ::std::string& value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
}
#if LANG_CXX11
inline void GffHeader_GenomeBuildDirective::set_source(::std::string&& value) {
  
  source_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
}
#endif
inline void GffHeader_GenomeBuildDirective::set_source(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
}
inline void GffHeader_GenomeBuildDirective::set_source(const char* value, size_t size) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
}
inline ::std::string* GffHeader_GenomeBuildDirective::mutable_source() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
  return source_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffHeader_GenomeBuildDirective::release_source() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
  
  return source_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffHeader_GenomeBuildDirective::set_allocated_source(::std::string* source) {
  if (source != NULL) {
    
  } else {
    
  }
  source_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.source)
}

// string name = 2;
inline void GffHeader_GenomeBuildDirective::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffHeader_GenomeBuildDirective::name() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
  return name_.GetNoArena();
}
inline void GffHeader_GenomeBuildDirective::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
}
#if LANG_CXX11
inline void GffHeader_GenomeBuildDirective::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
}
#endif
inline void GffHeader_GenomeBuildDirective::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
}
inline void GffHeader_GenomeBuildDirective::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
}
inline ::std::string* GffHeader_GenomeBuildDirective::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffHeader_GenomeBuildDirective::release_name() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffHeader_GenomeBuildDirective::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffHeader.GenomeBuildDirective.name)
}

// -------------------------------------------------------------------

// GffHeader

// string gff_version = 1;
inline void GffHeader::clear_gff_version() {
  gff_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffHeader::gff_version() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.gff_version)
  return gff_version_.GetNoArena();
}
inline void GffHeader::set_gff_version(const ::std::string& value) {
  
  gff_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffHeader.gff_version)
}
#if LANG_CXX11
inline void GffHeader::set_gff_version(::std::string&& value) {
  
  gff_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffHeader.gff_version)
}
#endif
inline void GffHeader::set_gff_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gff_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffHeader.gff_version)
}
inline void GffHeader::set_gff_version(const char* value, size_t size) {
  
  gff_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffHeader.gff_version)
}
inline ::std::string* GffHeader::mutable_gff_version() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.gff_version)
  return gff_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffHeader::release_gff_version() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffHeader.gff_version)
  
  return gff_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffHeader::set_allocated_gff_version(::std::string* gff_version) {
  if (gff_version != NULL) {
    
  } else {
    
  }
  gff_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gff_version);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffHeader.gff_version)
}

// repeated .nucleus.genomics.v1.Range sequence_regions = 2;
inline int GffHeader::sequence_regions_size() const {
  return sequence_regions_.size();
}
inline ::nucleus::genomics::v1::Range* GffHeader::mutable_sequence_regions(int index) {
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.sequence_regions)
  return sequence_regions_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::Range >*
GffHeader::mutable_sequence_regions() {
  // @@protoc_insertion_point(field_mutable_list:nucleus.genomics.v1.GffHeader.sequence_regions)
  return &sequence_regions_;
}
inline const ::nucleus::genomics::v1::Range& GffHeader::sequence_regions(int index) const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.sequence_regions)
  return sequence_regions_.Get(index);
}
inline ::nucleus::genomics::v1::Range* GffHeader::add_sequence_regions() {
  // @@protoc_insertion_point(field_add:nucleus.genomics.v1.GffHeader.sequence_regions)
  return sequence_regions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::Range >&
GffHeader::sequence_regions() const {
  // @@protoc_insertion_point(field_list:nucleus.genomics.v1.GffHeader.sequence_regions)
  return sequence_regions_;
}

// repeated .nucleus.genomics.v1.GffHeader.OntologyDirective feature_ontologies = 3;
inline int GffHeader::feature_ontologies_size() const {
  return feature_ontologies_.size();
}
inline void GffHeader::clear_feature_ontologies() {
  feature_ontologies_.Clear();
}
inline ::nucleus::genomics::v1::GffHeader_OntologyDirective* GffHeader::mutable_feature_ontologies(int index) {
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.feature_ontologies)
  return feature_ontologies_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >*
GffHeader::mutable_feature_ontologies() {
  // @@protoc_insertion_point(field_mutable_list:nucleus.genomics.v1.GffHeader.feature_ontologies)
  return &feature_ontologies_;
}
inline const ::nucleus::genomics::v1::GffHeader_OntologyDirective& GffHeader::feature_ontologies(int index) const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.feature_ontologies)
  return feature_ontologies_.Get(index);
}
inline ::nucleus::genomics::v1::GffHeader_OntologyDirective* GffHeader::add_feature_ontologies() {
  // @@protoc_insertion_point(field_add:nucleus.genomics.v1.GffHeader.feature_ontologies)
  return feature_ontologies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >&
GffHeader::feature_ontologies() const {
  // @@protoc_insertion_point(field_list:nucleus.genomics.v1.GffHeader.feature_ontologies)
  return feature_ontologies_;
}

// repeated .nucleus.genomics.v1.GffHeader.OntologyDirective attribute_ontologies = 4;
inline int GffHeader::attribute_ontologies_size() const {
  return attribute_ontologies_.size();
}
inline void GffHeader::clear_attribute_ontologies() {
  attribute_ontologies_.Clear();
}
inline ::nucleus::genomics::v1::GffHeader_OntologyDirective* GffHeader::mutable_attribute_ontologies(int index) {
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.attribute_ontologies)
  return attribute_ontologies_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >*
GffHeader::mutable_attribute_ontologies() {
  // @@protoc_insertion_point(field_mutable_list:nucleus.genomics.v1.GffHeader.attribute_ontologies)
  return &attribute_ontologies_;
}
inline const ::nucleus::genomics::v1::GffHeader_OntologyDirective& GffHeader::attribute_ontologies(int index) const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.attribute_ontologies)
  return attribute_ontologies_.Get(index);
}
inline ::nucleus::genomics::v1::GffHeader_OntologyDirective* GffHeader::add_attribute_ontologies() {
  // @@protoc_insertion_point(field_add:nucleus.genomics.v1.GffHeader.attribute_ontologies)
  return attribute_ontologies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >&
GffHeader::attribute_ontologies() const {
  // @@protoc_insertion_point(field_list:nucleus.genomics.v1.GffHeader.attribute_ontologies)
  return attribute_ontologies_;
}

// repeated .nucleus.genomics.v1.GffHeader.OntologyDirective source_ontologies = 5;
inline int GffHeader::source_ontologies_size() const {
  return source_ontologies_.size();
}
inline void GffHeader::clear_source_ontologies() {
  source_ontologies_.Clear();
}
inline ::nucleus::genomics::v1::GffHeader_OntologyDirective* GffHeader::mutable_source_ontologies(int index) {
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.source_ontologies)
  return source_ontologies_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >*
GffHeader::mutable_source_ontologies() {
  // @@protoc_insertion_point(field_mutable_list:nucleus.genomics.v1.GffHeader.source_ontologies)
  return &source_ontologies_;
}
inline const ::nucleus::genomics::v1::GffHeader_OntologyDirective& GffHeader::source_ontologies(int index) const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.source_ontologies)
  return source_ontologies_.Get(index);
}
inline ::nucleus::genomics::v1::GffHeader_OntologyDirective* GffHeader::add_source_ontologies() {
  // @@protoc_insertion_point(field_add:nucleus.genomics.v1.GffHeader.source_ontologies)
  return source_ontologies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::nucleus::genomics::v1::GffHeader_OntologyDirective >&
GffHeader::source_ontologies() const {
  // @@protoc_insertion_point(field_list:nucleus.genomics.v1.GffHeader.source_ontologies)
  return source_ontologies_;
}

// string species = 6;
inline void GffHeader::clear_species() {
  species_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GffHeader::species() const {
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.species)
  return species_.GetNoArena();
}
inline void GffHeader::set_species(const ::std::string& value) {
  
  species_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nucleus.genomics.v1.GffHeader.species)
}
#if LANG_CXX11
inline void GffHeader::set_species(::std::string&& value) {
  
  species_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nucleus.genomics.v1.GffHeader.species)
}
#endif
inline void GffHeader::set_species(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  species_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nucleus.genomics.v1.GffHeader.species)
}
inline void GffHeader::set_species(const char* value, size_t size) {
  
  species_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nucleus.genomics.v1.GffHeader.species)
}
inline ::std::string* GffHeader::mutable_species() {
  
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.species)
  return species_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GffHeader::release_species() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffHeader.species)
  
  return species_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GffHeader::set_allocated_species(::std::string* species) {
  if (species != NULL) {
    
  } else {
    
  }
  species_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), species);
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffHeader.species)
}

// .nucleus.genomics.v1.GffHeader.GenomeBuildDirective genome_build = 7;
inline bool GffHeader::has_genome_build() const {
  return this != internal_default_instance() && genome_build_ != NULL;
}
inline void GffHeader::clear_genome_build() {
  if (GetArenaNoVirtual() == NULL && genome_build_ != NULL) {
    delete genome_build_;
  }
  genome_build_ = NULL;
}
inline const ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective& GffHeader::_internal_genome_build() const {
  return *genome_build_;
}
inline const ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective& GffHeader::genome_build() const {
  const ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* p = genome_build_;
  // @@protoc_insertion_point(field_get:nucleus.genomics.v1.GffHeader.genome_build)
  return p != NULL ? *p : *reinterpret_cast<const ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective*>(
      &::nucleus::genomics::v1::_GffHeader_GenomeBuildDirective_default_instance_);
}
inline ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* GffHeader::release_genome_build() {
  // @@protoc_insertion_point(field_release:nucleus.genomics.v1.GffHeader.genome_build)
  
  ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* temp = genome_build_;
  genome_build_ = NULL;
  return temp;
}
inline ::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* GffHeader::mutable_genome_build() {
  
  if (genome_build_ == NULL) {
    auto* p = CreateMaybeMessage<::nucleus::genomics::v1::GffHeader_GenomeBuildDirective>(GetArenaNoVirtual());
    genome_build_ = p;
  }
  // @@protoc_insertion_point(field_mutable:nucleus.genomics.v1.GffHeader.genome_build)
  return genome_build_;
}
inline void GffHeader::set_allocated_genome_build(::nucleus::genomics::v1::GffHeader_GenomeBuildDirective* genome_build) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete genome_build_;
  }
  if (genome_build) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      genome_build = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, genome_build, submessage_arena);
    }
    
  } else {
    
  }
  genome_build_ = genome_build;
  // @@protoc_insertion_point(field_set_allocated:nucleus.genomics.v1.GffHeader.genome_build)
}

// -------------------------------------------------------------------

// GffReaderOptions

// -------------------------------------------------------------------

// GffWriterOptions

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace genomics
}  // namespace nucleus

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::nucleus::genomics::v1::GffRecord_Strand> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nucleus::genomics::v1::GffRecord_Strand>() {
  return ::nucleus::genomics::v1::GffRecord_Strand_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_nucleus_2fprotos_2fgff_2eproto
