#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Fri Apr 29 10:30:56 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class PanelBasicInfo(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelBasicInfo.__init__
        wx.Panel.__init__(self, *args, **kwds)
        self.label_18 = wx.StaticText(self, -1, "Name:")
        self.TextName = wx.TextCtrl(self, -1, "")
        self.label_19 = wx.StaticText(self, -1, "UUID:")
        self.StaticTextUUID = wx.StaticText(self, -1, "aaaaaaaa-1111-bbbb-2222-cccccccccccc")
        self.label_20 = wx.StaticText(self, -1, "Creator:")
        self.TextCreator = wx.TextCtrl(self, -1, "")
        self.Label_22 = wx.StaticText(self, -1, "Created:")
        self.StaticTextCreated = wx.StaticText(self, -1, "01 January 1001", style=wx.ALIGN_CENTRE)
        self.TextComment = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_WORDWRAP)
        self.sizer_1_copy_staticbox = wx.StaticBox(self, -1, "Project Comments")
        self.LabelMachineSettingsSummary = wx.StaticText(self, -1, "LabelMachineSettingsSummary")
        self.ButtonEditMachineSettings = wx.Button(self, -1, "Edit...")
        self.sizer_machine_settings_staticbox = wx.StaticBox(self, -1, "Machine Settings")
        self.TextCalcResolution = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, " steps")
        self.ComboBandwidthType = wx.ComboBox(self, -1, choices=["FW at Half Height", "FW at Maximum", "FW at Minimum"], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.sizer_master_params_staticbox = wx.StaticBox(self, -1, "Master Parameters")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.on_name, self.TextName)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_investigator, self.TextCreator)
        self.Bind(wx.EVT_BUTTON, self.on_edit_machine_settings, self.ButtonEditMachineSettings)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PanelBasicInfo.__set_properties
        self.TextName.SetMinSize((275, -1))
        self.TextComment.SetMinSize((100, 50))
        self.ComboBandwidthType.SetSelection(-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PanelBasicInfo.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_master_params_staticbox.Lower()
        sizer_master_params = wx.StaticBoxSizer(self.sizer_master_params_staticbox, wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(2, 3, 5, 0)
        self.sizer_machine_settings_staticbox.Lower()
        sizer_machine_settings = wx.StaticBoxSizer(self.sizer_machine_settings_staticbox, wx.HORIZONTAL)
        self.sizer_1_copy_staticbox.Lower()
        sizer_1_copy = wx.StaticBoxSizer(self.sizer_1_copy_staticbox, wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(4, 2, 5, 5)
        grid_sizer_1.Add(self.label_18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.TextName, 0, wx.EXPAND|wx.ALIGN_BOTTOM, 0)
        grid_sizer_1.Add(self.label_19, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.StaticTextUUID, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.TextCreator, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.Label_22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.StaticTextCreated, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_22.Add(grid_sizer_1, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 6)
        sizer_1_copy.Add(self.TextComment, 1, wx.LEFT|wx.EXPAND, 2)
        sizer_22.Add(sizer_1_copy, 1, wx.TOP|wx.BOTTOM|wx.EXPAND, 6)
        sizer_machine_settings.Add(self.LabelMachineSettingsSummary, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_machine_settings.Add(self.ButtonEditMachineSettings, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_22.Add(sizer_machine_settings, 0, wx.BOTTOM|wx.EXPAND, 10)
        label_1 = wx.StaticText(self, -1, "Calculation Resolution: ")
        grid_sizer_2.Add(label_1, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 2)
        grid_sizer_2.Add(self.TextCalcResolution, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.label_3, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
        label_2 = wx.StaticText(self, -1, "Bandwidth Type: ")
        grid_sizer_2.Add(label_2, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 2)
        grid_sizer_2.Add(self.ComboBandwidthType, 0, wx.EXPAND, 0)
        grid_sizer_2.Add((20, 20), 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_master_params.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        sizer_22.Add(sizer_master_params, 0, wx.BOTTOM|wx.EXPAND, 10)
        sizer_1.Add(sizer_22, 0, wx.EXPAND, 0)
        sizer_1.Add((20, 20), 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        # end wxGlade

    def on_name(self, event): # wxGlade: PanelBasicInfo.<event_handler>
        print "Event handler `on_name' not implemented!"
        event.Skip()

    def on_investigator(self, event): # wxGlade: PanelBasicInfo.<event_handler>
        print "Event handler `on_investigator' not implemented!"
        event.Skip()

    def on_edit_machine_settings(self, event): # wxGlade: PanelBasicInfo.<event_handler>
        print "Event handler `on_edit_machine_settings' not implemented!"
        event.Skip()

# end of class PanelBasicInfo


class MyFrame2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.PanelBasicInfo = PanelBasicInfo(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle("frame_3")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_18.Add(self.PanelBasicInfo, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_18)
        sizer_18.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame2


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_test = MyFrame2(None, -1, "")
    app.SetTopWindow(frame_test)
    frame_test.Show()
    app.MainLoop()
