
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-05T17:41:38-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6bd2aaac50b1d5cd661347b1d219e20a9b92851c",
 "version": "1.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
