
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-11T15:46:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d22967b54a00ad1146fb88714e59f7c19533eb4",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
