
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-30T11:09:09-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb13ba9101524a193418ccd3ac458a02f4cafe8f",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
