[tool.poetry]
name = "pupy"
version = "2.1.5"
description = "pretty useful python"
authors = ["jessekrubin <jessekrubin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
