# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buf.proto',
  package='buf',
  syntax='proto3',
  serialized_pb=_b('\n\tbuf.proto\x12\x03\x62uf\"\xa4\x04\n\x06\x43olumn\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x04type\x18\x03 \x01(\x0e\x32\x16.buf.Column.ColumnType\x12\x0f\n\x07present\x18\x04 \x01(\x0c\x12-\n\x0bstring_data\x18\x05 \x01(\x0b\x32\x16.buf.Column.StringDataH\x00\x12-\n\x0bnumber_data\x18\x06 \x01(\x0b\x32\x16.buf.Column.NumberDataH\x00\x12+\n\nrange_data\x18\x07 \x01(\x0b\x32\x15.buf.Column.RangeDataH\x00\x12\x0e\n\x06\x66ormat\x18\x08 \x01(\t\x12\x1a\n\x12visual_cardinality\x18\t \x01(\x01\x12\x18\n\x10\x64\x65pendency_level\x18\n \x01(\x05\x1a,\n\nStringData\x12\x0e\n\x06values\x18\x01 \x01(\x0c\x12\x0e\n\x06\x62reaks\x18\x02 \x01(\x0c\x1a\x1c\n\nNumberData\x12\x0e\n\x06values\x18\x01 \x01(\x0c\x1a\x37\n\tRangeData\x12\x14\n\x0cvalues_lower\x18\x01 \x01(\x0c\x12\x14\n\x0cvalues_upper\x18\x02 \x01(\x0c\"j\n\nColumnType\x12\n\n\x06STRING\x10\x00\x12\x07\n\x03INT\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\x12\r\n\tINT_RANGE\x10\x03\x12\x10\n\x0c\x44OUBLE_RANGE\x10\x04\x12\r\n\tDATE_TIME\x10\x05\x12\x0b\n\x07UNKNOWN\x10\x06\x42\x06\n\x04\x64\x61ta\"\x91\x01\n\x05Table\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\r\x12\r\n\x05\x62\x65gin\x18\x04 \x01(\r\x12\x0b\n\x03\x65nd\x18\x05 \x01(\r\x12\x0e\n\x06sample\x18\x06 \x01(\x08\x12\x13\n\x0brow_indices\x18\x07 \x01(\x0c\x12\x1c\n\x07\x63olumns\x18\x08 \x03(\x0b\x32\x0b.buf.Columnb\x06proto3')
)



_COLUMN_COLUMNTYPE = _descriptor.EnumDescriptor(
  name='ColumnType',
  full_name='buf.Column.ColumnType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT_RANGE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE_RANGE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATE_TIME', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=453,
  serialized_end=559,
)
_sym_db.RegisterEnumDescriptor(_COLUMN_COLUMNTYPE)


_COLUMN_STRINGDATA = _descriptor.Descriptor(
  name='StringData',
  full_name='buf.Column.StringData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='buf.Column.StringData.values', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='breaks', full_name='buf.Column.StringData.breaks', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=364,
)

_COLUMN_NUMBERDATA = _descriptor.Descriptor(
  name='NumberData',
  full_name='buf.Column.NumberData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='buf.Column.NumberData.values', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=394,
)

_COLUMN_RANGEDATA = _descriptor.Descriptor(
  name='RangeData',
  full_name='buf.Column.RangeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values_lower', full_name='buf.Column.RangeData.values_lower', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values_upper', full_name='buf.Column.RangeData.values_upper', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=451,
)

_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='buf.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='buf.Column.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='buf.Column.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='buf.Column.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='present', full_name='buf.Column.present', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='buf.Column.string_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_data', full_name='buf.Column.number_data', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_data', full_name='buf.Column.range_data', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='buf.Column.format', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visual_cardinality', full_name='buf.Column.visual_cardinality', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dependency_level', full_name='buf.Column.dependency_level', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COLUMN_STRINGDATA, _COLUMN_NUMBERDATA, _COLUMN_RANGEDATA, ],
  enum_types=[
    _COLUMN_COLUMNTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='buf.Column.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=19,
  serialized_end=567,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='buf.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='buf.Table.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='buf.Table.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='buf.Table.length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin', full_name='buf.Table.begin', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='buf.Table.end', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample', full_name='buf.Table.sample', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_indices', full_name='buf.Table.row_indices', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columns', full_name='buf.Table.columns', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=715,
)

_COLUMN_STRINGDATA.containing_type = _COLUMN
_COLUMN_NUMBERDATA.containing_type = _COLUMN
_COLUMN_RANGEDATA.containing_type = _COLUMN
_COLUMN.fields_by_name['type'].enum_type = _COLUMN_COLUMNTYPE
_COLUMN.fields_by_name['string_data'].message_type = _COLUMN_STRINGDATA
_COLUMN.fields_by_name['number_data'].message_type = _COLUMN_NUMBERDATA
_COLUMN.fields_by_name['range_data'].message_type = _COLUMN_RANGEDATA
_COLUMN_COLUMNTYPE.containing_type = _COLUMN
_COLUMN.oneofs_by_name['data'].fields.append(
  _COLUMN.fields_by_name['string_data'])
_COLUMN.fields_by_name['string_data'].containing_oneof = _COLUMN.oneofs_by_name['data']
_COLUMN.oneofs_by_name['data'].fields.append(
  _COLUMN.fields_by_name['number_data'])
_COLUMN.fields_by_name['number_data'].containing_oneof = _COLUMN.oneofs_by_name['data']
_COLUMN.oneofs_by_name['data'].fields.append(
  _COLUMN.fields_by_name['range_data'])
_COLUMN.fields_by_name['range_data'].containing_oneof = _COLUMN.oneofs_by_name['data']
_TABLE.fields_by_name['columns'].message_type = _COLUMN
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(

  StringData = _reflection.GeneratedProtocolMessageType('StringData', (_message.Message,), dict(
    DESCRIPTOR = _COLUMN_STRINGDATA,
    __module__ = 'buf_pb2'
    # @@protoc_insertion_point(class_scope:buf.Column.StringData)
    ))
  ,

  NumberData = _reflection.GeneratedProtocolMessageType('NumberData', (_message.Message,), dict(
    DESCRIPTOR = _COLUMN_NUMBERDATA,
    __module__ = 'buf_pb2'
    # @@protoc_insertion_point(class_scope:buf.Column.NumberData)
    ))
  ,

  RangeData = _reflection.GeneratedProtocolMessageType('RangeData', (_message.Message,), dict(
    DESCRIPTOR = _COLUMN_RANGEDATA,
    __module__ = 'buf_pb2'
    # @@protoc_insertion_point(class_scope:buf.Column.RangeData)
    ))
  ,
  DESCRIPTOR = _COLUMN,
  __module__ = 'buf_pb2'
  # @@protoc_insertion_point(class_scope:buf.Column)
  ))
_sym_db.RegisterMessage(Column)
_sym_db.RegisterMessage(Column.StringData)
_sym_db.RegisterMessage(Column.NumberData)
_sym_db.RegisterMessage(Column.RangeData)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), dict(
  DESCRIPTOR = _TABLE,
  __module__ = 'buf_pb2'
  # @@protoc_insertion_point(class_scope:buf.Table)
  ))
_sym_db.RegisterMessage(Table)


# @@protoc_insertion_point(module_scope)
