# Generated by Django 2.1.2 on 2018-10-22 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_type', models.CharField(blank=True, choices=[('PP', 'Частное лицо'), ('CO', 'Компания'), ('IE', 'Частный предприниматель')], default='PP', help_text='<details><ul><li>Частное лицо: заполняем ФИО, ИНН - не обязательно. Наименование  = ФИО</li><li>Частный предприниматель: заполняем ФИО, ИНН, полное наименование. Наименование  = ФИО (СПД-ФЛ)</li><li>Компания: заполняем Наименование, Полное наименование, ИНН, ЕГРПОУ</li></ul></details>', max_length=2, verbose_name='Тип контрагента')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('address_optional', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес (доп.)')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('zip', models.CharField(blank=True, default='', max_length=50, verbose_name='Почтовый индекс')),
                ('billing_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('bill_address_optional', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('bill_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('bill_zip', models.CharField(blank=True, default='', max_length=50, verbose_name='Почтовый индекс')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер телефона')),
                ('tax_number', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
