[tool.poetry]
name = "pysignald"
version = "0.0.1"
description = "A library that allows communication via the Signal IM service using the signald daemon."
authors = ["Stavros Korokithakis <hi@stavros.io>"]
packages = [{include = "signald"}]

[tool.poetry.dependencies]
python = "^3.4"
attrs = "^18.2"

[tool.poetry.dev-dependencies]
pytest = "^3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
