# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='priority',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('waiting', 'Waiting'), ('recurring', 'Recurring')], default='pending', max_length=9),
        ),
    ]
