# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import m6e.grpc_sdk.v2019_02.proto2.schema_pb2 as schema__pb2


class GetOffersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/proto2.GetOffers/Get',
        request_serializer=schema__pb2.GetOffersRequest.SerializeToString,
        response_deserializer=schema__pb2.GetOffersResponse.FromString,
        )


class GetOffersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetOffersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=schema__pb2.GetOffersRequest.FromString,
          response_serializer=schema__pb2.GetOffersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto2.GetOffers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CreateOffersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/proto2.CreateOffers/Create',
        request_serializer=schema__pb2.CreateOffersRequest.SerializeToString,
        response_deserializer=schema__pb2.CreateOffersResponse.FromString,
        )


class CreateOffersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CreateOffersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=schema__pb2.CreateOffersRequest.FromString,
          response_serializer=schema__pb2.CreateOffersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto2.CreateOffers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class UpdateOffersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Update = channel.unary_unary(
        '/proto2.UpdateOffers/Update',
        request_serializer=schema__pb2.UpdateOffersRequest.SerializeToString,
        response_deserializer=schema__pb2.UpdateOffersResponse.FromString,
        )


class UpdateOffersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UpdateOffersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=schema__pb2.UpdateOffersRequest.FromString,
          response_serializer=schema__pb2.UpdateOffersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto2.UpdateOffers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DeleteOffersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Delete = channel.unary_unary(
        '/proto2.DeleteOffers/Delete',
        request_serializer=schema__pb2.DeleteOffersRequest.SerializeToString,
        response_deserializer=schema__pb2.DeleteOffersResponse.FromString,
        )


class DeleteOffersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeleteOffersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=schema__pb2.DeleteOffersRequest.FromString,
          response_serializer=schema__pb2.DeleteOffersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto2.DeleteOffers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
