# Generated by Django 2.1.4 on 2018-12-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_utils', '0003_auto_20181210_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='priority',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('waiting', 'Waiting'), ('recurring', 'Recurring')], default='pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='testtaskduser',
            name='group',
            field=models.CharField(default='Public', max_length=120),
        ),
        migrations.AlterField(
            model_name='testtasknorelations',
            name='priority',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='testtasknorelations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('waiting', 'Waiting'), ('recurring', 'Recurring')], default='pending', max_length=9),
        ),
    ]
