# Generated by Django 2.1.3 on 2018-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_endorsement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='concession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='declared_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
