# coding: utf-8

# flake8: noqa

"""
    AdvoService Integration API

    External API for AdvoService  # noqa: E501

    OpenAPI spec version: 1.0.0-rc.1
    Contact: r.starenkiy@kf.ua
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0-rc.1"

# import apis into sdk package
from advoservice_integration.api.purchase_api import PurchaseApi

# import ApiClient
from advoservice_integration.api_client import ApiClient
from advoservice_integration.configuration import Configuration
# import models into sdk package
from advoservice_integration.models.message import Message
from advoservice_integration.models.purchase_request import PurchaseRequest
from advoservice_integration.models.user_details import UserDetails
