
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-28T14:20:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "786e6e89975a75d05683f0d92aefcc25c244f35e",
 "version": "1.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
