# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grr_response_proto/hunts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from grr_response_proto import semantic_pb2 as grr__response__proto_dot_semantic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grr_response_proto/hunts.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1egrr_response_proto/hunts.proto\x1a\x19google/protobuf/any.proto\x1a!grr_response_proto/semantic.proto\"\x85\x01\n\x04Hunt\x12\x0f\n\x07hunt_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12(\n\x0b\x63reate_time\x18\x03 \x01(\x04\x42\x13\xe2\xfc\xe3\xc4\x01\r\n\x0bRDFDatetime\x12-\n\x10last_update_time\x18\x04 \x01(\x04\x42\x13\xe2\xfc\xe3\xc4\x01\r\n\x0bRDFDatetime')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,grr__response__proto_dot_semantic__pb2.DESCRIPTOR,])




_HUNT = _descriptor.Descriptor(
  name='Hunt',
  full_name='Hunt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunt_id', full_name='Hunt.hunt_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Hunt.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='Hunt.create_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\374\343\304\001\r\n\013RDFDatetime'))),
    _descriptor.FieldDescriptor(
      name='last_update_time', full_name='Hunt.last_update_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\374\343\304\001\r\n\013RDFDatetime'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['Hunt'] = _HUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hunt = _reflection.GeneratedProtocolMessageType('Hunt', (_message.Message,), dict(
  DESCRIPTOR = _HUNT,
  __module__ = 'grr_response_proto.hunts_pb2'
  # @@protoc_insertion_point(class_scope:Hunt)
  ))
_sym_db.RegisterMessage(Hunt)


_HUNT.fields_by_name['create_time'].has_options = True
_HUNT.fields_by_name['create_time']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\374\343\304\001\r\n\013RDFDatetime'))
_HUNT.fields_by_name['last_update_time'].has_options = True
_HUNT.fields_by_name['last_update_time']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\374\343\304\001\r\n\013RDFDatetime'))
# @@protoc_insertion_point(module_scope)
