# Generated by Django 2.0.2 on 2018-02-21 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('electionnight', '0002_auto_20180218_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'geography'), ('model', 'division'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'government'), ('model', 'office'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'government'), ('model', 'body'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'electionnight'), ('model', 'pagetype'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
