# Generated by Django 2.0.2 on 2018-03-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20180206_2238'),
        ('electionnight', '0003_auto_20180221_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateColorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_order', to='election.Candidate')),
            ],
        ),
    ]
