# Generated by Django 2.0.8 on 2018-10-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionnight', '0007_pagecontent_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='featured',
            field=models.ManyToManyField(limit_choices_to={'election_day__slug': '2018-11-06'}, to='election.Election'),
        ),
    ]
