[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "gidgethub"
author = "Brett Cannon"
author-email = "brett@python.org"
home-page = "https://github.com/brettcannon/gidgethub"
requires = ["uritemplate>=3.0.0"]
requires-python = ">=3.6"
license = "Apache"
keywords = "github sans-io async"
description-file = "README.rst"
classifiers = ["Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
]

[tool.flit.metadata.requires-extra]
test = ["pytest>=3.0.0", "pytest-asyncio"]
doc = ["sphinx"]
# The 'dev' target should contain all dependencies listed in any extras coming
# after it to make sure that the test suite will run successfully.
dev = ["aiohttp", "mypy", "pytest-cov", "treq", "twisted[tls]", "tornado"]
aiohttp = ["aiohttp"]
treq = ["treq", "twisted[tls]"]
tornado = ["tornado"]

[tool.flit.metadata.urls]
Documentation = "https://gidgethub.readthedocs.io"
