
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f821a73577e6a114d0fb182cb36bf74f333f74fc",
 "version": "0.6.1-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
