- job:
    name: build-compute-hyperv-sphinx-docs
    parent: build-openstack-sphinx-docs
    description: |
      Run tox sphinx docs job with the nova dependency.
    vars:
      tox_install_siblings: true
    required-projects:
      - openstack/nova

- project:
    check:
      jobs:
        - build-openstack-releasenotes
        - build-compute-hyperv-sphinx-docs
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - build-openstack-releasenotes
        - build-compute-hyperv-sphinx-docs
        - openstack-tox-lower-constraints
