
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-13T16:55:13-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d5f835b8803a8ea25c6366dae3420179ff9c0f1",
 "version": "2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
