stages:
  - install
  - unittest
  - totaltest
  - deploy

#########################################
###### Installing all dependencies ######
#########################################
inst:
  stage: install
  script:
    - pip3 install --user -r requirements.txt


#########################################
##### Testing for single components #####
#########################################

unit:
  stage: unittest
  before_script:
    - python3 -m pip install --user pytest-cov
  script:
    - echo "Running unit tests for all python test cases"
    - python3 -m pytest -v --color=yes --cov .
  allow_failure: true

#########################################
###### Testing of the whole system ######
#########################################
linter:
  stage: totaltest
  before_script:
    - python3 -m pip install --user prospector
  script:
    - echo "Running linter for project"
    - python3 -m prospector -F -m -s veryhigh .

runtest:
  stage: totaltest
  script:
    - echo "Running a test of the whole system"
    - python3 . -s "Using Genetic Algorithm Approach to Reduce Register File Pressure during Instruction Scheduling"
    - python3 . 10.1109/SAMOS.2017.8344626

docu:
  stage: totaltest
  script:
    - echo "Checking for correct documentation"
    - python3 -m pep257 .
  before_script:
    - pip3 install --user pep257

#########################################
############# Deployment ################
#########################################

pypi:
  stage: deploy
  before_script:
    - python3 -m pip install --user --upgrade twine setuptools wheel
  script:
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload dist/*
  only:
    - tags
    - triggers
