
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-11T15:26:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5e71bd9de70f038d0079474bc50a5ace9965f89",
 "version": "1.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
