
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-14T14:57:11-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba819b9b94dc4bc79e1e32c34b51e296c3d2f608",
 "version": "1.3.0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
