version: '3'

services:

  eventbus:
    image: rabbitmq:alpine

  couchstore:
    image: treehouses/couchdb
    ports:
      - "5984:5984"
    # volumes:
    #   - "./couchdb:/opt/couchdb/data"

  sparksimulator:
    image: brewblox/firmware-simulator:develop

  spark:
    image: brewblox/brewblox-devcon-spark:develop
    privileged: true
    depends_on:
      - eventbus
      - couchstore
      - sparksimulator
    ports:
      - "5000:5000"
    volumes:
      - "./:/app/"
    command: >
      --device-host=sparksimulator
    #   --volatile
