[tool.poetry]
name = "tckn"
version = "1.0.0"
description = "A library for generating and validating Republic of Turkey identity numbers"
authors = ["Ekin Dursun <ekindursun@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
