# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('stem_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='bill_country',
            field=models.ForeignKey(help_text='Страна происхождения контрагента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_countries', to='cities_light.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='country',
            field=models.ForeignKey(help_text='Страна происхождения контрагента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country', verbose_name='Страна'),
        ),
    ]
