# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem_registration', '0004_auto_20181107_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='file1',
            field=models.ImageField(blank=True, upload_to='clients_data/'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='file2',
            field=models.ImageField(blank=True, upload_to='clients_data/'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='file3',
            field=models.ImageField(blank=True, upload_to='clients_data/'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='file4',
            field=models.ImageField(blank=True, upload_to='clients_data/'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='file5',
            field=models.ImageField(blank=True, upload_to='clients_data/'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='bill_country',
            field=models.ForeignKey(blank=True, help_text='Страна происхождения контрагента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_countries', to='cities_light.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Страна происхождения контрагента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country', verbose_name='Страна'),
        ),
    ]
