language: python
sudo: false
matrix:
  # Add or remove versions to match what Travis supports
  include:
    - python: '2.7'
      env: GIT_BUILDPACKAGE_SOURCE=xenial
    - python: '3.6'
      env: GIT_BUILDPACKAGE_SOURCE=bionic
    - python: '3.5'
      env: GIT_BUILDPACKAGE_SOURCE=master
    - python: '3.6'
      env: GIT_BUILDPACKAGE_SOURCE=master
install:
  - ./travisci/install.sh
script:
  - python setup.py test -v -a "--cov-config .coveragerc --cov=rhcephpkg"
after_success:
  - coveralls

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/v/flake8
