site_name: "Docker-buildpackage Documentation"
site_description: "A build and packaging tool and environment for OpenSwitch"
site_author: "OpenSwitch"
edit_uri: ""
nav:
  - Home: index.md
  - Changelog: changelog.md
  - Installation: installation.md
  - Building packages: build-packages.md
  - Building installers: build-installers.md
  - Comparison with opx-build: comparison.md
  - Apt Sources: apt-sources.md
  - Forking Upstream: forking-upstream.md
  - FAQs: faq.md
theme:
  name: "material"
  palette:
    primary: "deep orange"
    accent: "deep orange"
  font: false
repo_name: "opx-infra/dbp"
repo_url: "https://github.com/opx-infra/dbp"
extra:
  social:
    - type: "github"
      link: "https://github.com/open-switch"
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
