[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dbp"
author = "Dell inc."
author-email = "opx-infra@openswitch.net"
home-page = "https://openswitch.net"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.5,<4"
description-file="README.md"
requires = [
    "click",
    "controlgraph >=0.7.1",
    "colorama",
    "docker",
    "networkx",
    "pydot",
]

[tool.flit.metadata.requires-extra]
doc = [
    "mkdocs-material",
    "pygments",
    "pymdown-extensions",
]
test = [
    "coverage",
    "pytest",
    "pytest-cov",
]

[tool.flit.scripts]
dbp = "dbp:cli"
