[tool.poetry]
name = "send-sms-freemobile"
version = "0.1.0"
description = "Yet another tool to send SMS through French provider FreeMobile"
authors = ["Aloha68 <dev@aloha.im>"]
license = "ISC"
readme = "README.md"
homepage = "https://gitlab.com/aloha68/send-sms-freemobile"
repository = "https://gitlab.com/aloha68/send-sms-freemobile"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: Communications :: Telephony",
]

[tool.poetry.dependencies]
python = "^3.4"
requests = "^2.20"
xdg = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
send-sms = 'send_sms_freemobile:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
