
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-02T18:43:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "56d9911f6c8ab8ddc6c59783335a7b2a0596b912",
 "version": "3.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
