# Stubs for fabric.version (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

VERSION = ...  # type: Any

def git_sha(): ...
def get_version(form: str = ...): ...
