[tool.poetry]
name = "molib"
version = "0.1.0"
description = ""
authors = ["Manny Ochoa <manny@manuelochoa.com>"]

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
