
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-04T15:06:38-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb5133bb471eae881f272611d3678541e6070a68",
 "version": "1.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
