# Config file for automatic testing at travis-ci.org

sudo: required
dist: xenial
language: python
services:
    - docker
python:
    - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: docker-compose build && pip install tox

# Command to run tests, e.g. python setup.py test
jobs:
  include:
    - stage: Tests
      script: ./drun_app pytest
    - stage: Linting - flake8
      script: ./drun_app make lint
    - stage: Docs
      script: ./drun_app make docs
    - stage: packaging and Release
      script: ./drun_app make dist
