[tool.poetry]
name = "tckn"
version = "1.0.2"
description = "A library for generating and validating Republic of Turkey identity numbers"
authors = ["Ekin Dursun <ekindursun@gmail.com>"]
readme = "README.rst"
license = "MIT"
repository = "https://github.com/sdispater/poetry"
homepage = "https://github.com/sdispater/poetry"


[tool.poetry.dependencies]
python = "^3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
