
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-10T13:03:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "34cfe1dfeb14d57ce245f7b03dbc042aed7cd382",
 "version": "v1.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
