[tool.poetry]
name = "nobbofin-tools"
version = "0.1.1"
authors = ["Enno Lohmeier <enno@nerdworks.de>"]
#readme = "README.md"

packages = [
    { include="nobbofin_tools/importers" },
]

[tool.poetry.dependencies]
python = "^3.7"
beancount = "^2.1"
simplejson = "^3.16"

