language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install -U pip setuptools
    - pip install -U zc.buildout coverage coveralls
    - buildout
script:
    - coverage run bin/test -v
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
