# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2018-08-23 15:22:07
from __future__ import unicode_literals
import datetime

version = "2.0.4"
githash = "41a607235bdc335c9c125f828bdd35502a09aff9"


major = 2
minor = 0
bugfix = 4

release = True
timestamp = datetime.datetime(2018, 8, 23, 15, 22, 7)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
