
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-08T07:28:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cebf572f3e00a3b5a312a875e6b3ae190c1fedd",
 "version": "0.1.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
