language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install codecov pytest-cov setuptools
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py develop
script: pytest --cov=./
after_success:
  - codecov
