# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataStoreDto(Model):
    """DataStoreDto.

    :param name:
    :type name: str
    :param data_store_type: Possible values include: 'AzureBlob', 'AzureFile',
     'AzureDataLake', 'AzureSqlDatabase'
    :type data_store_type: str or ~_restclient.models.enum
    :param azure_storage_section:
    :type azure_storage_section: ~_restclient.models.AzureStorageDto
    :param azure_data_lake_section:
    :type azure_data_lake_section: ~_restclient.models.AzureDataLakeDto
    :param azure_sql_database_section:
    :type azure_sql_database_section: ~_restclient.models.AzureSqlDatabaseDto
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'data_store_type': {'key': 'dataStoreType', 'type': 'str'},
        'azure_storage_section': {'key': 'azureStorageSection', 'type': 'AzureStorageDto'},
        'azure_data_lake_section': {'key': 'azureDataLakeSection', 'type': 'AzureDataLakeDto'},
        'azure_sql_database_section': {'key': 'azureSqlDatabaseSection', 'type': 'AzureSqlDatabaseDto'},
    }

    def __init__(self, name=None, data_store_type=None, azure_storage_section=None, azure_data_lake_section=None, azure_sql_database_section=None):
        super(DataStoreDto, self).__init__()
        self.name = name
        self.data_store_type = data_store_type
        self.azure_storage_section = azure_storage_section
        self.azure_data_lake_section = azure_data_lake_section
        self.azure_sql_database_section = azure_sql_database_section
