
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-20T11:30:44+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d789cefb8a4e43571c2487e5dd3134a0c65fed0",
 "version": "2.0.0-alpha.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
