
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-10T13:35:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fbd14ed52aad1a4c479d92fad4c7e80f8526169",
 "version": "1.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
