---
- hosts: undercloud
  vars:
    metadata:
      name: Verify undercloud fits the disk space requirements to perform an upgrade
      description: >
        Make sure that the root partition on the undercloud node is large
        enough before starting an upgrade

        http://tripleo.org/environments/environments.html#id5
      groups:
        - pre-upgrade
    volumes:
      - {mount: /var/lib/docker,      min_size: 10}
      - {mount: /var/lib/config-data, min_size: 3}
      - {mount: /var,                 min_size: 16}
      - {mount: /,                    min_size: 20}
    a_mounts: "{{hostvars[inventory_hostname].ansible_facts.mounts}}"

  tasks:
  - include_tasks: tasks/disk_space.yaml
