image: registry.gitlab.com/theblueskyjunkie/registry-images/contactlist-build:0.1.0

variables:
  FLIT_ROOT_INSTALL: 1
  PACKAGE_NAME: contactList


stages:
  - build
  - test
  - deploy


.wheel-build: &build-wheel
  script:
    - '/venv/bin/flit build --format wheel'

  artifacts:
    paths:
      - dist/*.whl


.sdist-build: &build-sdist
  script:
    - '/venv/bin/flit build --format sdist'

  artifacts:
    paths:
      - dist/*.tar.gz


.restrict-feature: &feature-restricted
  only:
    - branches
    - master
  except:
    - tags


.restrict-tags: &tags-restricted
  only:
    # Semantic version tags https://semver.org
    - /^\d+\.\d+\.\d+$/
  except:
    - branches


.acquire-version: &acquire-tagged-version
  before_script:
    - echo ${CI_COMMIT_REF_NAME} > ${PACKAGE_NAME}/VERSION


build-wheel-package:
  stage: build

  # Use the default VERSION file for feature branches (0.0.0)
  <<: [ *build-wheel, *feature-restricted ]


build-wheel-release-package:
  stage: build

  <<: [ *acquire-tagged-version, *build-wheel, *tags-restricted ]


build-source-package:
  stage: build

  # Use the default VERSION file for feature branches (0.0.0)
  <<: [ *build-sdist, *feature-restricted ]


build-source-release-package:
  stage: build

  <<: [ *acquire-tagged-version, *build-sdist, *tags-restricted ]


unittests:
  stage: test

  before_script:
    - '/venv/bin/flit install'
  script:
    - '/venv/bin/nosetests
         --with-xunit
         --with-cov
         --cov-config .coveragerc
         --logging-level=INFO
         --cov-report term-missing
         --cov-report html
         --cov-report xml
         --cov ${PACKAGE_NAME}'

  artifacts:
    reports:
      junit: nosetests.xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


wheel-install-test:
  stage: test
  dependencies:
    - build-wheel-package

  script:
    - '/venv/bin/pip3 install dist/${PACKAGE_NAME}*.whl'

  <<: *feature-restricted


source-install-test:
  stage: test
  dependencies:
    - build-source-package

  script:
    - '/venv/bin/pip3 install dist/${PACKAGE_NAME}*.tar.gz'

  <<: *feature-restricted


# http://samb.io/blog/2016/devops/python/gitlab/continuous-deployment/continuous-deployment-to-python-packaging
deploy-pypi:
  dependencies:
    - build-wheel-release-package
    - build-source-release-package
  stage: deploy
  variables:
    FLIT_USERNAME: SECURE
    FLIT_PASSWORD: SECURE

  script:
    - '/venv/bin/flit publish'

  <<: [ *tags-restricted, *acquire-tagged-version ]
