# Signal Sources
RAW = "RAW"
TRANSFORMED = "TRANSFORMED"
CYTON = "CYTON"
GANGLION = "GANGLION"
ENOBIO = "ENOBIO"
SINE = "SINE"
NOISE = "NOISE"
RECORDING = "RECORDING"

# Frequency Bands
DELTA = (0, 4)
THETA = (4, 7.5)
ALPHA_MU = (7.5, 12)
BETA = (16, 31)
GAMMA = (31, 100)


# Transforms
FFT= "FFT"
PWELCH = "PWELCH"

# Data Modes
RAW = "raw"
TRANSFORMED = "Transformed"