name: stsci.skypac
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy
  - graphviz
  - matplotlib
  - numpy
  - numpydoc
  - spherical-geometry
  - sphinx
  - stsci.imagestats
  - stsci.tools
  - stwcs
  - pip:
    - sphinx_rtd_theme
    - git+https://github.com/spacetelescope/stsci_rtd_theme.git#egg=stsci_rtd_theme
