[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "parallelic"
version = "0.1.2"
license = "MPL-2.0"
description = "Hyper-parallel multi-node task execution engine"
authors = ["golyalpha <golyalpha@gmail.com>"]
readme = "readme.md"
repository = "https://gitlab.com/OnDev-Project/parallelic"
classifiers = [
	"Development Status :: 1 - Planning"
]

[tool.poetry.dependencies]
python = "^3.7"
pyzmq = "^17.1"
pytest-cov = "^2.6"


[tool.poetry.dev-dependencies]
pylint = "^2.2"
pytest = "^4.0"
toml = "^0.10.0"

[tool.poetry.scripts]
parallelic = "parallelic:main"
