language: python
dist: xenial
cache: pip
python:
  - 3.6
  - 3.7
  - pypy3.5
env:
  global:
    - PYTEST_ADDOPTS="-n auto --cov-config setup.cfg -o xfail_strict=1"
    - PYTHONHASHSEED=0
  matrix:
    - SPLIT=1/3
    - SPLIT=2/3
    - SPLIT=3/3
addons:
  apt:
    packages:
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - graphviz
stages:
  - quality
  - test
  - deploy
matrix:
  include:
    - python: 3.5
      env: SPLIT='1/3' COVERAGE='on'
    - python: 3.5
      env: SPLIT='2/3' COVERAGE='on'
    - python: 3.5
      env: SPLIT='3/3' COVERAGE='on'
    - stage: quality
      python: 3.5
      env: COVERAGE='on'
      script:
        - python -We:invalid -m compileall -f diofant -q
        - travis_wait python setup.py flake8
        - travis_wait 30 pylint -j1 diofant
        - python setup.py build_sphinx -W -b html
        - |
          if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
            rm -rf build/
            python setup.py build_sphinx -W -b linkcheck
          fi
        - pip uninstall -y gmpy2
        - DIOFANT_GROUND_TYPES='gmpy' py.test --cov diofant diofant/domains
        - travis_wait py.test --cov diofant --cov-append diofant/polys
    - stage: deploy
      env:
        -
      script: skip
      deploy:
        provider: pypi
        user: skirpichev
        password:
          secure: "OCi5YeQKvjr62Yzg1Bq9/xzIVDJSlr3q3YICp/gfnoPxTmiOiOug/Q\
                   SM0rxl929Rb9hvf/QuNI6bpkPs0lz2roXa0PdJ2pdoNOm5Md2e43ht\
                   bMRfH54YS98QDxL+gwasr327iGLi++avxF3N+vSyWboJLkSydDDlVh\
                   B7k/t57Ig="
        distributions: "sdist bdist_wheel"
        on:
          tags: true
  allow_failures:
    - python: pypy3.5
      env: SPLIT=3/3
install:
  - pip install --pre -U 'gmpy2;platform_python_implementation!="PyPy"'
  - travis_wait pip install .[exports,plot,interactive,develop,docs]
script:
  - |
    if [ -n "${COVERAGE}" ]; then
      python setup.py test --addopts "--cov diofant --ignore diofant/tests -m \"not slow and not xfail\" --split=${SPLIT}"
    else
      python setup.py test --addopts "--split=${SPLIT}"
    fi
after_success: test -n "${COVERAGE}" && codecov
notifications:
  email: false
